### ISSUE TITLE
Licensing URL error

### ISSUE THREAD

**Issue by gbirchmeier** [quickfix/quickfix#101]
From "Jim H" email to ask@:

> Just so you know, your in-source-code copyright notice contains a dead link.
> 
> It says in many source files:
> *\* See http://www.quickfixengine.org/LICENSE for licensing information.
> 
> However, if you go to that URL, it just displays the same web page as at any URL. So I think the URL is out of date.
> 
> I was able to find the licensing information, but I thought you would like to be made aware of this issue.

Can we simply restore that page to the main site?

**Comment by orenmnero** [comment]
It's back.
