### ISSUE TITLE
Sending Username with Logon request

### ISSUE THREAD

**Issue by benjfield** [quickfix/quickfix#103]
Hi, I am trying to work out how to send a username (and a couple of other fields) with a logon request. Can anyone suggest how I might go about doing that?

**Comment by mgatny** [comment]
Do it in the toAdmin() callback.  Example here:
https://github.com/mgatny/quickfix_101/blob/master/src/Workspace.cpp#L109-129

-- 
Mike Gatny
Connamara Systems, LLC

**Comment by benjfield** [comment]
Ah, I see.

Perfect, got that working.
