### ISSUE TITLE
std::bad_alloc 

### ISSUE THREAD

**Issue by sbhujabal** [quickfix/quickfix#107]
I am getting std::bad_alloc exception while calling quickfix from python code. 
Please provide some solution.

**Comment by sbhujabal** [comment]
My pyhton code is calling quickfix library; however I am getting std::bad_alloc exception. 
How to throw cause C++ exception to be thrown to python so that it can be handled in python code.

**Comment by muratkarakus7** [comment]
Unfortunately, it seems that there is no easy way to do it, rather than exporting exception by capturing bad_alloc and tweaking swig configuration file to propagate to python.

http://stackoverflow.com/questions/15006048/dynamically-rethrowing-self-defined-c-exceptions-as-python-exceptions-using-sw

**Comment by orenmnero** [comment]
Not enough information
