### ISSUE TITLE
Build failed for QuickFix/C++ 1.14.3 in VisualStudio 2015

### ISSUE THREAD

**Issue by tonyfortune** [quickfix/quickfix#114]
We change the line of code in Utility.cpp according to the advice on
https://github.com/quickfix/quickfix/issues/81

However, we still get lot of errors like
Error   LNK2019 unresolved external symbol __imp_ntohs referenced in function "short __cdecl FIX::socket_hostport(int)" (?socket_hostport@FIX@@YAFH@Z)
Error   LNK2019 unresolved external symbol __imp_WSAStartup referenced in function "void __cdecl FIX::socket_init(void)" (?socket_init@FIX@@YAXXZ)

Does anyone able to build it in VS2015 and gives some advice?

**Comment by kmiklas** [comment]
+1
