### ISSUE TITLE
Why there are two identical sessions in executor.cfg?

### ISSUE THREAD

**Issue by ghost** [quickfix/quickfix#117]
Is this sth like double buffering?

[SESSION]
BeginString=FIX.4.0
SenderCompID=EXECUTOR
TargetCompID=CLIENT1
FileStorePath=store
DataDictionary=../spec/FIX40.xml

[SESSION]
BeginString=FIX.4.0
SenderCompID=EXECUTOR
TargetCompID=CLIENT2
FileStorePath=store
DataDictionary=../spec/FIX40.xml

**Comment by mgatny** [comment]
On Thu, Oct 27, 2016 at 9:27 AM, dagorlad <notifications@github.com> wrote:

> TargetCompID=CLIENT1
>
> TargetCompID=CLIENT2
>

Different target comp IDs, so you can attach more than one client (e.g.
tradeclient)

-- 
Mike Gatny

**Comment by muratkarakus7** [comment]
Makes sense, thank you!

---
