### ISSUE TITLE
Forum Apply for Membership Crash

### ISSUE THREAD

**Issue by kmiklas** [quickfix/quickfix#124]
Howdy,

I tried to apply for membership to the Quickfix at the following URL...
http://www.quickfixengine.org/forum/people.php?PostBackAction=ApplyForm

..but it crashed:

![Apply for Membership Crash](http://www.miklas.org/images/quickfixForumCrash.png)

Any advice?

Thx,
Keith :^)

**Comment by orenmnero** [comment]
Forum has been discontinued.
