### ISSUE TITLE
FIX::DoubleConvertor::convert can return incorrect values.

### ISSUE THREAD

**Issue by marmysh** [quickfix/quickfix#137]
My auto tests detected that FIX::DoubleConvertor::convert function can return incorrect value. I understand that this error is very small, but even a small error can be important.

# Program:
const char* st = "1.66251";
double x = 166251.0 / 100000;
double y = atof(st);
double z = FIX::DoubleConvertor::convert(st);

std::cout << "(y - x) = " << (x - y) << std::endl;
std::cout << "(z - x) = " << (z - x) << std::endl;
std::cout << "(z - y) = " << (z - y) << std::endl;

# Console output:
(y - x) = 0
(z - x) = 2.22045e-16
(z - y) = 2.22045e-16

**Comment by Ambal** [comment]
Hi, @marmysh . This is known issue and you should either 1) revert to using atof() function OR 2) pick up appropriate fix from https://github.com/quickfix/quickfix/pull/92
