### ISSUE TITLE
Just a question about karopawil's fork. Not an issue.

### ISSUE THREAD

**Issue by karopawil** [quickfix/quickfix#141]
Hi,

I have been maintaing a fork of the QuickFix lib which is basically has stuff that we need for our products.

1. OpenSSL support.

The SSL functionality is contained in the files

ThreadedSSLSocketAcceptor.h
ThreadedSSLSocketAcceptor.cpp
ThreadedSSLSocketInitiator.h
ThreadedSSLSocketInitiator.cpp
ThreadedSSLSocketConnection.h
ThreadedSSLSocketConnection.cpp
UtilitySSL.h
UtilitySSL.cpp

Also required minor changes to a couple of other headers as needed protected access.

2. SunOS (sparc) and AIX support (in addition to Windows and Linux). There were compile problems (AIX/SunOS) and crashes (unaligned access) with the original on sparc.

3. Order of fields/tags for outgoing messages can be specified (configurable, not on by default). This was required for the EMX platform (a variation of FIX protocol). QuickFIX for performance reasons has fields in ascending order (apart from group order, header/trailer etc.). I am not even sure that the way I have implemented is the best way but it works for us.

4. There is also some EMX platform related functionality which can be enabled through a compile flag.

Would these be of interest for the main QuickFix Repo? It seems that some people are using the SSL functionality and it would be better for them to use the original QuickFIX.

Regards

**Comment by quickfix** [comment]
Yes, will definitely look into these. Thanks for the hard work, much appreciated!
