### ISSUE TITLE
Unable to build QuickFix (C++) on Linux

### ISSUE THREAD

**Issue by rhtiwari** [quickfix/quickfix#143]
Hi,
    While building QuickFix on Linux using the command
 ./configure && make

I get the following error:
mv -f .deps/DictionaryTestCase.Tpo .deps/DictionaryTestCase.Plo
mv: cannot stat `.deps/DictionaryTestCase.Tpo': No such file or directory

Could you explain what I am doing wrong, please?

Thanks in advance for your help.

Regards
rhtiwari

**Comment by ctubio** [comment]
try `./bootstrap && ./configure && make `

**Comment by orenmnero** [comment]
We would need more information on your toolchain to help our here. Operating system, compiler etc.
