### ISSUE TITLE
Is there any configuration to switch between different sessions at runtime automatically?

### ISSUE THREAD

**Issue by thirdson** [quickfix/quickfix#148]
Things like we are client/initiator we connect to our server, we may have several backup server, when one server down like retry more than 5 time can possible switch to another session automatically? we notice there is a SessionQualifier properties, but not sure where we can control it? as always we configuration only one session.  Thanks!

**Comment by thirdson** [comment]
so like I have sessions : all their configuration are same, startString, Sender, Targer etc, only different is IP
1. main
2. back1
3. back2
//  I notice there is API 
```
bool Session::sendToTarget( Message& message, const std::string& qualifier )
```

need every time I need specify a qualifier? notice the initiator already keep list:

```
  SessionIDs m_pending;
  SessionIDs m_connected;
  SessionIDs m_disconnected;
```

but #lookupSession in fact find from the Sessions' session list, so those two are not sync?  can automatically find the first live session?

**Comment by orenmnero** [comment]
Yes, if you want to share the the same comp ids, you will need a session qualifier to distinguish them. You will need to determine yourself which session is live. 

If these are cold failovers where only one session will be connected, you can use logons to determine which one is active. 

If they are hot failovers that are always connected, you will need to make some determination on which ones to send messages to.

You can listen to all the sessions at the same time, so receiving messages should just work.
