### ISSUE TITLE
Usage with File input for parsing

### ISSUE THREAD

**Issue by kariya2** [quickfix/quickfix#151]
Sorry, I have a newb usage question. Is there any way to use the parser from quickfix with a FIX file?

**Comment by orenmnero** [comment]
Yes, the Message object can take a string. You can pass messages you read from a file into there. You may need to also supply a data dictionary if the messages you are parsing have repeating groups.

**Comment by kariya2** [comment]
thanks oren. I tried using a data dicitonary as you suggested but this is the bug I am facing 

https://github.com/quickfix/quickfix/issues/154

Thanks!
