### ISSUE TITLE
Unable to get file pointer position from D:\FixStore\FIX.4.4-ABC.body

### ISSUE THREAD

**Issue by SumitGuupta** [quickfix/quickfix#152]
We are getting number of Fix Events for 10-15 secs:
               FIX event    IO Error: IO Error: Unable to get file pointer position from D:\FixStore\FIX.4.4-ABC.body,

after this the below events are logged:
2.  Connection reset error as below:  
               FIX event    Socket Error: Connection reset by peer.

3.  Disconnection error as below:
                FIX event    Disconnecting.

4.  Logon requests:
                FIX event    Logon contains ResetSeqNumFlag=Y, reseting sequence numbers to 1
                FIX event    Received logon request.

Could anyone help me out to understand whats the issue here?

Thanks in Advance.

**Comment by lwfcatch** [comment]
Getting Configuration Failed Error: Could not open body file while client (initiator) trying to logon after logout
