### ISSUE TITLE
Data Dictionary, complex XML values

### ISSUE THREAD

**Issue by kariya2** [quickfix/quickfix#154]
I'm trying to parse CME data with repeating NoMDEntry groups. 

` FIX50SP2::MarketDataIncrementalRefresh::NoMDEntries group;`

If I build the message as such : 
`FIX::Message(string, false)`  
  `msg.hasGroup(group)`

hasGroup returns false even though field 268 exists in the message.
I tried using a data dictionary to solve this

`std::istream dict("FIX50SP2.XML")`
`FIX::Dictionary dictionary(dict);`
`FIX::Message(string, dictionary, false)`
`msg.hasGroup(group)`

returns true as it should 

However 

`msg.getField(mdUpdateAction)`
`msg.getField(mdEntryType)`

and 

`group.getField(mdUpdateAction)`
`group.getField(mdEntryType)`

etc fail saying field not found.

It does manage to successfully 
`msg.getField(transactTime)`
`msg.getField(NoMDEntries)`

So I am a little confused, I looked at FIX50SP2.XML and TransactTime and NoMDEntries have no possible enum values in the XML but other 2 do. I was wondering if this had something to do with it. 

And if not I was hoping someone would have insight into why this might be happening

**Comment by Ambal** [comment]
Hi, @kariya2. Do you get an exception when you call 

FIX::Message(string, dictionary, true);

This FIX::Message constructor should validate your messasge after parsing is complete. Also note, that you for FIX50+ messages you should use a constructor which takes both session and application data dictionaries:

/// Construct a message from a string using a session and application data dictionary
  Message( const std::string& string, const FIX::DataDictionary& sessionDataDictionary,
           const FIX::DataDictionary& applicationDataDictionary, bool validate = true )
  throw( InvalidMessage );

**Comment by kariya2** [comment]
Hey @Ambal thanks for getting back to me. Yes it says my headers are out of order. 

I'm using data from this archive here
ftp://ftp.cmegroup.com/sbe_sample_data/historical_data/
(specifically XCBT_MD_ZS_FUT_20160315). 

I am relatively new to this protocol so I was wondering what dicitonary versions to use for application and session in this case

Thanks again!

**Comment by kariya2** [comment]
Hey just as an update I tried constructing the message with 2 dictionaries and it worked. However for some reason it's still throwing Field no found for msg.getGroup(num, group) in some instances. 

` FieldMap& getGroupRef( int num, int tag ) const ` 
 ` throw( FieldNotFound )  `
 ` {  `
    `Groups::const_iterator i = m_groups.find( tag );`
    `if( i == m_groups.end() ) throw FieldNotFound( tag );`
    `if( num <= 0 ) throw FieldNotFound( tag );`
    `if( i->second.size() < (unsigned)num ) throw FieldNotFound( tag );`
    `return *( *(i->second.begin() + (num-1) ) );`
  `}`

I found out through gdb that its failing at 
    `if( i->second.size() < (unsigned)num ) throw FieldNotFound( tag );`

However I only try to access msg.getGroup(num, group) in a loop which has condition
num <= mdEntries.value(). So I'm really lost on what's going on. 

Note: It's not failign for all messages just some

**Comment by Ambal** [comment]
Hi, @kariya2. I think your problem is with condition
```
num <= mdEntries.value()
```

The code inside getGroupRef() requires an INDEX as 'num' parameter, so it has to start from 0 (zero) and your condition above must be
```
num < mdEntries.value()
```

**Comment by Ambal** [comment]
Hi @kariya2. There is a problem with CME message decoding using standard FIX dictionaries - the custom field 5798 must be included in order to properly parse the repeating NoMDEntry groups. Add the definition to the FIX50.xml and you should be fine.

**Comment by kariya2** [comment]
Hey @Ambal  yeah I think that was the issue, thankfiully the groups with those fields weren't particularly relevant to me so I was able to get around it. Thanks a lot for your help!
