### ISSUE TITLE
Microsecond precision

### ISSUE THREAD

**Issue by ekrel** [quickfix/quickfix#156]
Due to MIFID2 requirements certain venues will now send microsecond precision timestamps. Currently receiving such a value will result in an exception being thrown for incorrect format:

20171020-08:04:43.504 : Initiated logon request
20171020-08:04:43.517 : Message 1 Rejected: Incorrect data format for value:52
20171020-08:04:43.517 : Tried to send a reject while not logged on
20171020-08:04:53.508 : Timed out waiting for logon response
20171020-08:04:53.508 : Disconnecting

Changing spec to use 52 as string (to get output):
20171020-08:54:41.131 : Initiated logon request
20171020-08:54:41.144 : Incorrect data format for value: 20171020-08:54:42.574193
20171020-08:54:41.144 : Disconnecting

**Comment by Ambal** [comment]
Hi, @ekrel . Quickfix does not support microsecond timestamps yet so, unffortunately. There were patches from other users which introduce this functionality but I can't find the link.
P.S. Some venues like Tradition allow you to disable microsecond timestamps with MiFID2.

**Comment by oroian-raul** [comment]
Hi @ekrel , I am using pull request 155. It has microsecond support. Works very well for me.

**Comment by karopawil** [comment]
Can try https://github.com/karopawil/quickfix

TimestampPrecision=6

(0-9 is possible)

**Comment by orenmnero** [comment]
Master branch now has up to nano precision.
