### ISSUE TITLE
Cannot build quickfix on Mac Sierra. Plz help

### ISSUE THREAD

**Issue by hunghoang** [quickfix/quickfix#157]
After run:
./bootstrap
./configure
make
It shows:
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:693:39: error:
      no member named 'fabsf' in the global namespace; did
      you mean simply 'fabsf'?
abs(float __lcpp_x) _NOEXCEPT {return ::fabsf(__lcpp_x);}
                                      ^~
/usr/include/math.h:430:14: note: 'fabsf' declared here
extern float fabsf(float);
             ^
In file included from FieldConvertors.cpp:36:
In file included from ./double-conversion/fixed-dtoa.cc:28:
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:697:40: error:
      no member named 'fabs' in the global namespace; did
      you mean simply 'fabs'?
abs(double __lcpp_x) _NOEXCEPT {return ::fabs(__lcpp_x);}
                                       ^~
/usr/include/math.h:431:15: note: 'fabs' declared here

**Comment by Ambal** [comment]
Hi, @hunghoang . Please, check if #161 will resolve your build issue.

**Comment by hunghoang** [comment]
Ok @Ambal 
I will check it. Thanks

**Comment by hunghoang** [comment]
Hi @Ambal 
It still shows a lot of errors:
-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in TestUnitTest++.o
      construction vtable for std::__1::basic_ostream<char, UnitTest::MemoryOutStream::char_traits<char> >-in-UnitTest::MemoryOutStream in TestTest.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [TestUnitTest++] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by orenmnero** [comment]
Are you still seeing this? I just tried with the latest master and it built ok.

**Comment by orenmnero** [comment]
Closing. Will re-open if you report the issue still exists.

**Comment by hunghoang** [comment]
It's ok
