### ISSUE TITLE
How to config tag #OdbcStoreConnectionString in quickfix for python?

### ISSUE THREAD

**Issue by rinleit** [quickfix/quickfix#171]
I have some information about ODBC database.

**cat /etc/odbcinst.ini** 
[Oracle]
Description = Oracle Driver
Driver = /usr/lib/oracle/12.1/client64/lib/libsqora.so.12.1
FileUsage = 1
Driver Logging = 7

**cat /etc/odbc.ini** 
[MyOracleDB]
Description = My Oracle DB
Driver = Oracle
Trace = yes
TraceFile = /tmp/odbc_oracle.log
Database = //xxx.xxx.xxx.xxx:1521/COREDB
UserID = quickfix
Password = xxxxxx
Port = 1521

How can I configure it for quickfix and check that it is successfully connected?

OdbcStoreUser=sa
OdbcStorePassword=password
OdbcStoreConnectionString=DATABASE=quickfix;DRIVER={SQL Server};SERVER=(local);

The default of quickfix is the same as above.
I have tried many ways but still no results.

Many thanks,
Sorry for my english is not good.

**Comment by booboothefool** [comment]
were you able to get the database integration to work?
