### ISSUE TITLE
Uninitialized FIX::SocketException::errorToWhat

### ISSUE THREAD

**Issue by hiltmon** [quickfix/quickfix#174]
On Mac and Linux, when compiling with c++11, get a lot of these warnings. Does not affect runtime but is annoying when compiling against the library. I set -Wuninitialized in my projects, but I do not like doing that. 

```
In file included from ../../include/quickfix/FieldConvertors.h:30:
../../include/quickfix/Exceptions.h:283:77: warning: base class 'FIX::SocketException' is uninitialized when used here to access 'FIX::SocketException::errorToWhat' [-Wuninitialized]
    : SocketException( size == 0 ? "Connection reset by peer." : size < 0 ? errorToWhat() : "Success." ) {}
```

**Comment by orenmnero** [comment]
Mader errorToWhat static so it can be called in initializer list safely.
