### ISSUE TITLE
how to separate client-only files? 

### ISSUE THREAD

**Issue by gminorcoles** [quickfix/quickfix#185]
Hi,
 this may be a weird question but is is straightforward to find all the files that only pertain to creating messages on the client? For deployment reasons I might want to split things up. I have code that only creates messages, with not access to a session or any other run-time facilities, and it passes the messages on to code that does interact with the session. 

It would make things easier if I could take all the message and field headers and implementation and put it in a separate unit of compilation. I am having a hard time even finding the implementations, starting at a place like fix44 NewOrderSingle. I guess a lot is implemented in the headers.

**Comment by orenmnero** [comment]
I'm not really sure how it makes things easier. It might make things a little smaller maybe? The easiest thing in my mind is to deploy the projects as is, that way you know everything is there, no guessing.
