### ISSUE TITLE
build in docker file fails during ./bootstrap

### ISSUE THREAD

**Issue by gminorcoles** [quickfix/quickfix#186]
I am trying to build quickfix in a Dockerfile.  Here is the dockerfile:

FROM ubuntu

CMD ["/sbin/my_init"]

#WORKDIR ?

run apt update 
run apt -y install g++ 
run apt -y install git
run apt -y install automake
run apt -y install libtool 
run apt -y install libxml2 
run apt -y install libxml2-dev 
run apt -y install xsltproc 
run apt -y install jruby 
run apt -y install ruby 
run apt -y install ruby-dev 
run apt -y install libmysqlclient-dev 
run apt -y install libpq-dev 
run apt -y install mysql-server postgresql

run mkdir /src
WORKDIR /src
run git clone https://gminorcoles:p3dantic@github.com/gminorcoles/tsalib.git
#https://username:password@github.com/username/repo_name.git

WORKDIR /src/tsalib/quickfix-master
#run ["/bin/pwd"]
#run ["/bin/ls"]
#run autoreconf
run ./bootstrap 
run ./configure
run ./make
run sudo make install

RUN apt-get clean && rm -rf /var/lib/apt//lists/* /tmp/* /var/tmp/* 

Running docker build -< Dockerfile results in this output - at the end is an error in ./bootstrap complaining about the directory test/cfg does not exist. Can anyone help? I took the packages to install from the build bash scripts in this repository. But since a docker container is essentially a fresh install, maybe there is something else I need?

Step 20/24 : run ./bootstrap
 ---> Running in bf191e2ca42a
+ uname
+ libtoolize --copy
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ autoreconf -i -Wall,no-obsolete
configure.ac:33: warning: cannot check for file existence when cross compiling
../../lib/autoconf/general.m4:2788: AC_CHECK_FILE is expanded from...
m4/ax_lib_stlport.m4:1: AX_LIB_STLPORT is expanded from...
configure.ac:33: the top level
configure.ac:33: warning: cannot check for file existence when cross compiling
../../lib/autoconf/general.m4:2788: AC_CHECK_FILE is expanded from...
m4/ax_lib_stlport.m4:1: AX_LIB_STLPORT is expanded from...
configure.ac:33: the top level
configure.ac:23: installing 'config/compile'
configure.ac:26: installing 'config/config.guess'
configure.ac:26: installing 'config/config.sub'
configure.ac:19: installing 'config/install-sh'
configure.ac:19: installing 'config/missing'
Makefile.am: installing './COPYING' using GNU General Public License v3 file
Makefile.am:     Consider adding the COPYING file to the version control system
Makefile.am:     for your code, to avoid questions about which license your project uses
configure.ac:275: error: required file 'quickfix.pc.in' not found
configure.ac:275: error: required file 'test/cfg/Makefile.in' not found
examples/executor/C++/Makefile.am: installing 'config/depcomp'
examples/ordermatch/test/Makefile.am:2: warning: 'CXXFLAGS' is a user variable, you should not override it;
examples/ordermatch/test/Makefile.am:2: use 'AM_CXXFLAGS' instead
examples/ordermatch/test/Makefile.am:14: warning: 'LDFLAGS' is a user variable, you should not override it;
examples/ordermatch/test/Makefile.am:14: use 'AM_LDFLAGS' instead
/usr/share/automake-1.15/am/ltlibrary.am: warning: 'libquickfix.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
src/C++/Makefile.am:5:   while processing Libtool library 'libquickfix.la'
/usr/share/automake-1.15/am/ltlibrary.am: warning: 'libquickfixcpptest.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
src/C++/test/Makefile.am:4:   while processing Libtool library 'libquickfixcpptest.la'
src/C++/test/Makefile.am:2: warning: 'CXXFLAGS' is a user variable, you should not override it;
src/C++/test/Makefile.am:2: use 'AM_CXXFLAGS' instead
src/Makefile.am:24: warning: 'LDFLAGS' is a user variable, you should not override it;
src/Makefile.am:24: use 'AM_LDFLAGS' instead
/usr/share/automake-1.15/am/ltlibrary.am: warning: '_quickfix.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
src/python/Makefile.am:2:   while processing Libtool library '_quickfix.la'
test/Makefile.am:1: error: required directory test/cfg does not exist
parallel-tests: installing 'config/test-driver'
autoreconf: automake failed with exit status: 1
The command '/bin/sh -c ./bootstrap' returned a non-zero code: 1

**Comment by gminorcoles** [comment]
I was using a quickfix version from late 2017. By doing git clone from the current github repo, the script ran through and quickfix was built in docker.

this is the script so far

FROM ubuntu

CMD ["/sbin/my_init"]

#WORKDIR ?

run apt update 
run apt -y install build-essential
run apt -y install make
run apt -y install g++ 
run apt -y install git
run apt -y install automake
run apt -y install libtool 
run apt -y install libxml2 
run apt -y install libxml2-dev 
run apt -y install xsltproc 
run apt -y install jruby 
run apt -y install ruby 
run apt -y install ruby-dev 
run apt -y install libmysqlclient-dev 
run apt -y install libpq-dev 
#run apt -y install mysql-server postgresql

run mkdir /src
WORKDIR /src
#run git clone https://gminorcoles:p3dantic@github.com/gminorcoles/tsalib.git
run git clone https://github.com/quickfix/quickfix.git
#https://username:password@github.com/username/repo_name.git

WORKDIR /src/quickfix
#run ["/bin/pwd"]
#run ["/bin/ls"]
#run autoreconf
run ./bootstrap 
run ./configure
run make
run make install

ENV LD_LIBRARY_PATH="/usr/local/lib"
run echo ${LD_LIBRARY_PATH}

RUN apt-get clean && rm -rf /var/lib/apt//lists/* /tmp/* /var/tmp/*

**Comment by orenmnero** [comment]
Can this be closed then?

**Comment by gminorcoles** [comment]
I thnk so. I will admit that as an inexperienced linux c++ developer, I am not happy that I don't understand why the problem accidentally went away after using a slightly newer version of quickfix.
