### ISSUE TITLE
Logging timestamps need to be fixed to  use precision

### ISSUE THREAD

**Issue by karopawil** [quickfix/quickfix#187]
Conversions like

UtcTimeStampConvertor::convert(m_time, m_millisecondsInTimeStamp) 

give single digit precision/scale like

<20180305-14:52:49.3, FIX.4.2:CLIENT1->EXECUTOR, outgoing>

**Comment by robertbetts** [comment]
I have looked at the various issues and PRs and the currently source code support for fractional timestamps. 

Has anyone on the OSX experienced a constant zero milliseconds. If I add :
` MillisecondsInTimeStamp=Y`
` TimestampPrecision=6 `
to my config I can see in SendingTime, zero padding result, however it is always .000000

**Comment by karopawil** [comment]
If you look in FieldTypes.cpp you will see _POSIX_SOURCE or HAVE_FTIME. Are any of these defined for your build? Also, how are you building it? With configure and make?

**Comment by robertbetts** [comment]
Yes, I saw those defines and I guessed that I was either defaulting to time(0) or these was a difference on my platform. I could not seem to find these defines are set to after looking in the generated Makefile. 
yes I am using ./configure and make. Could you point me to where I could see the result.

**Comment by karopawil** [comment]
Closing this as this has been fixed.
