### ISSUE TITLE
Locating a Python desktop trading app on remote server is realistic? 

### ISSUE THREAD

**Issue by nomadcreator** [quickfix/quickfix#191]
I am considering to make a small trading program using QuickFIX+Python for trade. 

What I am thinking is making a small trading app written by Python and put that on remote server close to the market, and run it 24 hours. 

However, what I found is this QuickFIX requires C++ environment, and when I download it, it was several gyga bites. I am not sure about how this works, but if I need to install C++ environment on remote server, I am afraid I also need to upload giga bytes environment on the server, and that seems to be not easy. 

I would like to ask you some very preliminary questions: 
1) What I am going to do is feasible? 
2) Should I install Visual Studio C++ environment on remote server to run the Python desktop app?

**Comment by jordanbaucke** [comment]
@nomadcreator 

1. Yes it is feasible. Yes, your hosted environment may need a larger amount of disk space to store data for both application execution environments (Visual C++ and other Windows-OS runtime tools are pretty  bulky)
2. It's possible to build and run C++ applications like quickfix on Windows or Linux (easier some would argue on linux operating systems) If you want to use Visual C++ / Python you can get a hosted Windows Server w/ a remote desktop GUI and your necessary binaries, and monitor the program from a GUI or SSH server.
