### ISSUE TITLE
'tr1/memory':No such file or directory' for Python installation

### ISSUE THREAD

**Issue by nomadcreator** [quickfix/quickfix#192]
I am using Python and trying to install QuickFIX by following command

>pip install quickfix

Then, I see error message as below and cannot complete

>test_std_tr1_shared_ptr.cpp(1): fatal error C1083: include cannot open file   'tr1/memory':No such file or directory

What is the issue? How this can be solved? 

My environments are as below:
- Windows10
- Python 3.5

**Comment by HeinrichShneilmanhousr** [comment]
Same issues here. Still can't install!

**Comment by whoan** [comment]
I made a PR (#202) to solve a related problem. I think yours should also be fixed.

**Comment by tomasgomezpizarro** [comment]
I think that in this stackoverflow [question](https://stackoverflow.com/questions/36852426/how-do-i-install-quickfix-for-python) the same problem is discussed and an alternative solution is offered by installing quickfix from this [page](https://www.lfd.uci.edu/~gohlke/pythonlibs/). I hope it works.

**Comment by orenmnero** [comment]
Latest master no longer includes this file

**Comment by CplusPython23** [comment]
> I think that in this stackoverflow [question](https://stackoverflow.com/questions/36852426/how-do-i-install-quickfix-for-python) the same problem is discussed and an alternative solution is offered by installing quickfix from this [page](https://www.lfd.uci.edu/~gohlke/pythonlibs/). I hope it works.

Would you happen to have the pre-built wheel for QF 1.15.1 still available and if yes, could you share it?
