### ISSUE TITLE
Incorrect data format from AvgPx

### ISSUE THREAD

**Issue by samuelrohr** [quickfix/quickfix#193]
Getting this message from fix:
8=FIX.4.29=31835=834=8052=20180426-20:04:43.89137=8678593834198=868375138711=32c01f7007414408804816d56edc935c17=86410:5700:120=0150=239=21=935040255=ARZZ354=238=10040=244=50.5159=032=10031=50.51336=1151=014=1006=50,51000075=2018042660=20180426-20:04:43.89621=11057=N6032=14010=101

I try to get the AvgPx from field 44, doing like (Python3):
t = tag_type()
if not msg.isSetField(t): return None
msg.getField(t)  # t is equal to 6=50,510000
return t.getValue()

after that a error is raised.

**Comment by christian-quisbert** [comment]
Hi @samuelrohr! Try this:
`
...
return t.getString()
`

**Comment by orenmnero** [comment]
The error would be helpful, I assume you got InvalidDataFormat which it is. So yeah you will need to pull it out as a string
