### ISSUE TITLE
question : how correctly read all FIX messages from FileStore

### ISSUE THREAD

**Issue by RomanShestakov** [quickfix/quickfix#194]
Hello - 
apologies if this is not the right place to ask questions.

what is the correct way to deal with the following scenario - in my application, on restart,  I need to be able to build in-memory list of ids of messages which have been already submitted to the current FIX session.

This requirement is related to the recovery logic of the application - to make sure that duplicated messages are not submitted to the session again. 

I don't see  any ready-to-use APIs for this (but maybe I am mistaken) -  what is the best way to archive this? Open the store file and just parse each message separentley looking at start / end of message tags? Or there is some better way?

**Comment by orenmnero** [comment]
QuickFIX handles resend logic, it will never send the same message twice unless the other side indicates that it has not received the message.

To answer your question regardless, there is a get method on store. So if you wanted to get all the messages:

store.get(0, store.getNetTargetMsgSeqNum())
