### ISSUE TITLE
PossDupFlag handling

### ISSUE THREAD

**Issue by karopawil** [quickfix/quickfix#195]
According to FIX documentation:

PossDupFlag <43> — if a message with this sequence number has been previously received, ignore message, if not, process normally.

As far as I can tell in session.cpp, these messages are not being forwarded. Shouldn't an application callback be made in the case when this flag is set?

**Comment by orenmnero** [comment]
What does “as far as I can tell mean?”

Why do you think this?

**Comment by karopawil** [comment]
There is no "fromCallback" in "doPossDup" or after that. verify just returns false.

**Comment by karopawil** [comment]
Sequence numbers should not be changed so verify returning false is fine.

**Comment by karopawil** [comment]
I think it is fine the way it is done in quickfix. The other application is sending a sequence reset before sending resend messages, which leads to the problem.
