### ISSUE TITLE
Python: Class OrderCancelReject does not have the group "NoPartyIDs".

### ISSUE THREAD

**Issue by christian-quisbert** [quickfix/quickfix#199]
In [quickfix50sp2.py](https://github.com/quickfix/quickfix/blob/master/src/python/quickfix50sp2.py), the message **OrderCancelReject** does not define the NoPartyIDs class.

	class OrderCancelReject(Message):
		def __init__(self):
			Message.__init__(self)
			self.getHeader().setField( fix.MsgType("9") )

The standard fix defines the **Parties** Block, to allow different types of entities.

- [x] Add an internal class to this message to define the missing group in the python file.

**Comment by christian-quisbert** [comment]
**_Add the following lines to solve this:_**

In [quickfix50sp2.py](https://github.com/quickfix/quickfix/blob/master/src/python/quickfix50sp2.py) line 1027 add the following to the "OrderCancelReject" class:

	class OrderCancelReject(Message):
		def __init__(self):
			Message.__init__(self)
			self.getHeader().setField( fix.MsgType("9") )

		class NoPartyIDs(fix.Group):
			def __init__(self):
				order = fix.IntArray(5)
				order[0] = 448
				order[1] = 447
				order[2] = 452
				order[3] = 802
				order[4] = 0
				fix.Group.__init__(self, 453, 448, order)

			class NoPartySubIDs(fix.Group):
				def __init__(self):
					order = fix.IntArray(3)
					order[0] = 523
					order[1] = 803
					order[2] = 0
					fix.Group.__init__(self, 802, 523, order)

And then, add the following **component** line in [FIX50SP2.xml](http://www.quickfixengine.org/FIX50SP2.xml):

	<message name='OrderCancelReject' msgtype='9' msgcat='app'>
		...
		<component name='Parties' required='N' />
	</message>
Resolved #199 .

**Comment by christian-quisbert** [comment]
I leave the issue open until I commit with the solution.

**Comment by orenmnero** [comment]
Parties does not belong to OrderCancelReject according to the 5.0SP2 specification

https://www.onixs.biz/fix-dictionary/5.0.SP2/msgType_9_9.html
