### ISSUE TITLE
quickfix 1.14.3 failed to compile when specifying --with-mysql=<mysql libs>

### ISSUE THREAD

**Issue by ephraimstevens** [quickfix/quickfix#200]
I'm using gcc 8.1 and compiling the entitled version of quickfix on a Redhat 6.9 64-bit machine.  

When omitting the --with-mysql option, the software compiles fine.  When using the --with-mysql option the following compiler error is thrown:

In file included from ../MySQLStore.h:37,
                 from MySQLStoreTestCase.cpp:31:
../MySQLConnection.h: In member function ‘void FIX::MySQLConnection::connect()’:
**../MySQLConnection.h:177:5: error: ‘my_bool’ was not declared in this scope
     my_bool reconnect = 1;**
     ^~~~~~~
../MySQLConnection.h:177:5: note: suggested alternative: ‘Symbol’
     my_bool reconnect = 1;
     ^~~~~~~
     Symbol
../MySQLConnection.h:178:76: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&FIX::MySQLConnection::reconnect’ [-fpermissive]
     mysql_options( m_pConnection, MYSQL_OPT_RECONNECT, static_cast<char*>(&reconnect) );
                                                                            ^~~~~~~~~
../MySQLConnection.h:178:85: error: invalid static_cast from type ‘bool (FIX::MySQLConnection::*)()’ to type ‘char*’
     mysql_options( m_pConnection, MYSQL_OPT_RECONNECT, static_cast<char*>(&reconnect) );

It appears that type **my_bool** is not declared anywhere else in the quickfix source code.  However,  grepping the source reveals this type only to be referenced once. And this one occurrence is found in file src/C++/MySQLConnection.h.  The specific location is approximately around line 177:

![image](https://user-images.githubusercontent.com/14278160/42238259-366e595c-7ece-11e8-891a-2ae4a52aba0b.png)

The fix/workaround is to comment out the **my_bool** type and set the type to a char.  This is the only way I could get the compiler to stop complaining.

My questions are: 

1) Is this a bug?  
2) Will my workaround break the behavior of my quickfix installation? 
3) Why isn't my_bool declared anywhere else in the quickfix source of 1.14.3?
4) Will this issue be/Is this issue fixed in a later version of quickfix?

Thank you.

                                                                                     ^

**Comment by orenmnero** [comment]
It’s a typeset declared in the MySQL library. Looks like they now name it book in MySQL 8.0.1 I suggest adding another version check which uses the new type.

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling

**Comment by orenmnero** [comment]
Sorry, not ‘book’, ‘bool’

**Comment by Jimmy1500** [comment]
Is there an update on this one?

I am still facing the same issue using quickfix 1.15.1.
Changing my_bool to char will get rid of the compiling error but won't connect to MySQL database:
```
app         | terminate called after throwing an instance of 'FIX::ConfigError'
app         |   what():  Configuration failed: Unable to connect to database [MySQL server has gone away]
```
I can confirm my database configuration is correct. Same configuration works for my other apps that doesn't use quickfix.

**Comment by orenmnero** [comment]
Hi Jimmy,

I didn't see it mentioned, what version of MySQL are you trying to connect to? And is it on the same box as quickfix or is it a remote connection?

**Comment by Jimmy1500** [comment]
Hi oren,
Here are a few things I have tried:
Before said code change
* build quickfix 1.15.1 against MySQL 5.7 -> compiler error
* build quickfix 1.15.1 against MySQL 8.0 -> compiler error
After code change:
* connect quickfix app to MySQL 8.0 -> FIX::ConfigError (above mentioned)

And I have tried connecting to database spun up directly at localhost:3306 or as container with exposed ports via docker-compose.

**Comment by orenmnero** [comment]
#450
