### ISSUE TITLE
arm compilation fail

### ISSUE THREAD

**Issue by ctubio** [quickfix/quickfix#206]
```
bad instruction `lock'
bad instruction `xadd'
```
since: https://github.com/quickfix/quickfix/commit/6339473775cb01622166011b9ebe72750210bb5e

because: https://github.com/quickfix/quickfix/blob/b7c346f81a772ada7dd0bb0ea7b6a0962c8cec69/src/C%2B%2B/AtomicCount.h#L161-L168

:gift:

**Comment by Johan3F** [comment]
I'm still being bitten by this... 
Is there any reason why assembly code was used instead of standard C++?

**Comment by ctubio** [comment]
only the author knows, but you can just remove the assembly and uncomment the commented c++

**Comment by quickfix** [comment]
As the comment says, looks like the whole class was just copied from the
boost x86 implementation.

https://www.boost.org/doc/libs/1_55_0/boost/smart_ptr/detail/atomic_count_gcc_x86.hpp

We shouldn't have x86 specific code in quickfix, unless it is conditionally
applied. Will probably just switch to using the generic C++ code, but also
should evaluate if we need this atomic count class at all.

**Comment by Johan3F** [comment]
I think that just uncommenting the piece of code won't do any good. The whole operation must be an atomic one.
I got a solution in place using std::atomic. 
How can I do to create a PR for this?

**Comment by orenmnero** [comment]
Create a branch with your changes. Github will allow you to do a PR from
that branch.

The only thing to consider is the use of std:atomic will put us firmly
supporting only c++11 and up. Probably ok, it's probably time. But there
has been some resistance to that move in the past.

**Comment by Johan3F** [comment]
Perfect. If no c++11, I'll have to use mutexes and that was the previous version solution... I'll create a PR once I managed to get my hand on a computer again and then we'll see what the reaction is.
Thanks for the information :)

**Comment by Johan3F** [comment]
So, I finally managed to get a computer after holidays. I have the fix in place in a local branch. I don't have push rights for the repo. Should I pass it to somebody with rights, or should I ask for push permits? What suits all best?
In the end I went for the mutex instead of std::atomic to avoid the C++11 controversy

**Comment by quickfix** [comment]
You can fork and submit a pull request.

**Comment by Johan3F** [comment]
PR os ready for review

**Comment by bxb** [comment]
I'm running into this problem as well. It seems like @Johan3F has a PR out to fix it. Is there anything blocking that PR from being merged?

**Comment by orenmnero** [comment]
#430
