### ISSUE TITLE
executor.py: Wrong number or type of arguments for overloaded function ‘new_StringField’.

### ISSUE THREAD

**Issue by smorrel1** [quickfix/quickfix#213]
Think there's a str() missing from executor.py. 
ERROR
-------
NotImplementedError: Wrong number or type of arguments for overloaded function ‘new_StringField’.
(8=FIX.4.29=12935=D34=14149=CLIENT152=20181101-12:29:26.30300056=EXECUTOR11=221=138=240=244=254=155=EURUSD59=060=20181101-12:29:1010=201)
Traceback (most recent call last):
 File “../examples/executor/python/executor.py”, line 43, in fromApp
   executionReport.setField( fix.OrderID(self.genOrderID()) )
 File “/Applications/anaconda/envs/bunnies/lib/python3.5/site-packages/quickfix.py”, line 40662, in __init__
   quickfix.StringField.__init__(self, 37, data)
 File “/Applications/anaconda/envs/bunnies/lib/python3.5/site-packages/quickfix.py”, line 910, in __init__
   this = _quickfix.new_StringField(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function ‘new_StringField’.
 Possible C/C++ prototypes are:
   FIX::StringField::StringField(int,std::string const &)
   FIX::StringField::StringField(int)

Correction: executor.py, line 66
-------------------------------
	def genOrderID(self):
		self.orderID = self.orderID+1
		return str(self.orderID)  # self.orderID
	def genExecID(self):
		self.execID = self.execID+1
		return str(self.execID)  # self.execID

Similar issue [here](https://github.com/quickfix/quickfix/issues/196#issue-327242969) on bytes vs string restriction in python 3.

**Comment by orenmnero** [comment]
#460
