### ISSUE TITLE
Python 2.7 Postgres messages_log not working???

### ISSUE THREAD

**Issue by rive072** [quickfix/quickfix#221]
I'm trying to move the FileLogs to a Postgres database. This Linux Python 2.7 and Postgres 9.5. I created the database and the required supporting messages_log and event_log tables. However, the app won't event attempt to write the logs to Postgres. I don't even see it try to attempt a connection to the database. Postgres is running on the localhost. I confirmed that the os installed python Quickfix 1.2 was built with Postgres support. Additionally I reinstalled Quickfix 1.5 using pip install in a separate virtualenv and still no luck. Any advice?  

Here's my client.cf - replaced private info with xxx
----------------------------------------
[DEFAULT]
ConnectionType=initiator
HeartBtInt=30
ReconnectInterval=60
FileStorePath=store
FileLogPath=log
StartTime=00:00:00
EndTime=00:00:00
ReconnectInterval=5
ResetOnDisconnect=N
ResetOnLogout=N
UseDataDictionary=Y
ValidateUserDefinedFields=N

[SESSION]
BeginString=FIX.4.2
SenderCompID=FIX_TEST
TargetCompID=FIX_CLIENT
SocketConnectPort=31000
SocketConnectHost=localhost
DataDictionary=FIX42.xml
PostgreSQLLogDatabase=XXX_20181127
PostgreSQLLogUser=xxx
PostgreSQLLogHost=localhost

----------------------------------------------------------
### OUTPUT OF POSTGRES DB ###

psql -U xxx -h localhost -d XXX_20181127 -c "\d"
                 List of relations
 Schema |         Name          |   Type   | Owner  
--------+-----------------------+----------+--------
 public | event_log             | table    | xxx
 public | event_log_sequence    | sequence | xxx
 public | messages_log          | table    | xxx
 public | messages_log_sequence | sequence | xxx
 
-----------------------------------------------------------
### SAMPLE CODE - VERY SIMPLE APP  - SEND AN ORDER AND RECEIVED EXECUTION MESSAGE ###
import sys
import time
import signal
import argparse
import psycopg2
import quickfix as fix
from datetime import datetime
from os import path

# The Fix Application class    
class Application(fix.Application):
    today = int(datetime.now().strftime('%Y%m%d'))
    
    orderID = 0
    execID = orderID
    
    def gen_ord_id(self):
        self.orderID += 1
        return self.orderID

    def __init__(self, verbose):
        fix.Application.__init__(self)
        self.verbose = verbose

    def onCreate(self, sessionID):
        print ("Created session: '{}'".format(sessionID.toString()))

    def onLogon(self, sessionID):
        self.sessionID = sessionID
        print ("Successful connected: '{}'".format(sessionID.toString()))

    def onLogout(self, sessionID):
        print ("Disconnected: '{}'".format(sessionID.toString()))

    def toAdmin(self, message, sessionID):
        if self.verbose:
            print ("toAdmin: {} {}".format(sessionID.toString(), message.toString()))

    def fromAdmin(self, message, sessionID):
        if self.verbose:
            print ("fromAdmin: {} {}".format(sessionID.toString(), message.toString()))

    def toApp(self, message, sessionID):
        if self.verbose:
            print ("toApp: {} {}".format(sessionID.toString(), message.toString()))

    def fromApp(self, message, sessionID):
        if self.verbose:
            print ("fromApp: {} {}".format(sessionID.toString(), message.toString()))
        msgType = fix.MsgType()
        message.getHeader().getField(msgType)

        # Check for MessageType 35=8 (ExecutionReport) and pass it to FixMessageStorage otherwise just log it
        if msgType.getValue() == fix.MsgType_ExecutionReport:
           self.ExecutionMessageProcess(message, sessionID)
        else:
           print ('Unexpected Message: {}:{}'.format(sessionID.toString(), message.toString()))

    # Process the Execution Message        
    def ExecutionMessageProcess(self, message, sessionID):
        print message.toString()

    def genOrderID(self):
        self.orderID += 1
        return '{}{:02d}'.format(str(self.today), self.orderID)

    def genExecID(self):
        self.execID += 1
        return `self.execID`

    def put_order(self):
        print("Creating the following order: ")
        order = fix.Message()
        order.getHeader().setField(fix.BeginString(fix.BeginString_FIX42)) #
        order.getHeader().setField(fix.MsgType(fix.MsgType_NewOrderSingle)) #39=D
        order.setField(fix.ClOrdID(self.genOrderID())) #11=Unique order

        order.setField(fix.HandlInst(fix.HandlInst_MANUAL_ORDER_BEST_EXECUTION)) #21=3 (Manual order, best executiona)
        order.setField(fix.Symbol('SMBL')) #55=SMBL ?
        order.setField(fix.Side(fix.Side_BUY)) #43=1 Buy
        order.setField(fix.OrdType(fix.OrdType_LIMIT)) #40=2 Limit order
        order.setField(fix.OrderQty(100)) #38=100
        order.setField(fix.Price(10))
        order.setField(fix.TransactTime())
        if self.verbose:
            print order.toString()
        try:
            fix.Session.sendToTarget(order, self.sessionID)
        except fix.SessionNotFound as e:
            print (e)
            return
        

def main(args):
    # Define the progname based on the system arguments
    progname = sys.argv[0].split(".")[0]

    print ('Starting: {}'.format(progname))

    try:    
        # Initiate the FIX class object and parameters
        application = Application(args.verbose)
        settings = fix.SessionSettings(args.filename)
        storeFactory = fix.FileStoreFactory(settings)
        logFactory = fix.FileLogFactory(settings)
        initiator = fix.SocketInitiator(application, storeFactory, settings,  logFactory)
        initiator.start()

        while True:
            time.sleep(2)
            application.put_order()

        initiator.stop()    

    except (fix.ConfigError, fix.RuntimeError) as e:
        print (e)

    return 0

if __name__=='__main__':

    parser = argparse.ArgumentParser(description='FIX Message Relay And Storage')
    parser.add_argument('filename', nargs='?', help='Name of fix session file', default='fixsession.session')
    parser.add_argument('-v', help='verbose', action='store_true', dest='verbose', default=False)
    args = parser.parse_args()
    sys.exit(main(args))

**Comment by makarov-roman** [comment]
@rive072 were you able to get things working?

**Comment by rive072** [comment]
Unfortunately no, I never got it to work. I tried different config entries with no luck. For some reason the PSQL log factory under python never initializes.

**Comment by huydangquoc** [comment]
I'm facing similar issue with python3, trying to make quickfix python works with postgresql support but no luck so far.
I'm able to build the lib with postgresql support. Quite sure the lib is built successfully as i'm able to run my app like before where I install the lib via pip. In detail I used below commands to build:
```
./bootstrap
./configure --with-python3 --with-postgresql
make
make check
````

I'm also able to create needed db and tables by using `create.sh` script under `src/sql/postgresql`

My session config similar to @rive072 
```
[DEFAULT]
...
[SESSION]
...
# POSTGRESQL
PostgreSQLStoreDatabase=quickfix
PostgreSQLStoreUser=p*****
PostgreSQLStorePassword=p*****
PostgreSQLStoreHost=localhost
PostgreSQLStorePort=5432
PostgreSQLStoreUseConnectionPool=N
...
```
but seem like these configs are not taking into account as no matter correct or wrong they are, nothing happen, no record saved to db or any return error.

I'm wondering which steps I may missed, or, does it work for anyone else?

**Comment by booboothefool** [comment]
has anyone actually gotten the postgres integration to work?

**Comment by PskovitinA** [comment]
Same question. Is there a way to configure python app to work with postgres? My greatest gratitude to anyone who can help.

> 
> 
> has anyone actually gotten the postgres integration to work?

**Comment by mattyoungberg** [comment]
Seems like a huge oversight, as the structure of `quickfix.py` shows that it allots variables for the PostgreSQL and MySQL configurations, but then just never implements corresponding factories needed to build the application object.

**Comment by mattyoungberg** [comment]
Pinging @orenmiller , do you guys know about the Python interface not exposing the db store and log factories?

**Comment by quickfix** [comment]
I believe they are available if you build from source. But not if you pip install it. Probably could get it to work with the package, but we would have to detect or be supplied the location of the library.

**Comment by orenmnero** [comment]
#504

**Comment by yaroslavhdev** [comment]
Hi @orenmnero ! Thank you for update. When do we get a new version available via pip install?
