### ISSUE TITLE
import quickfix on python messes up signal handlers?

### ISSUE THREAD

**Issue by kevlubkcm** [quickfix/quickfix#226]
running the below code and hitting `CTRL+C` results in a stack trace and `hello` printed

```
import time
try:
    time.sleep(100)
finally:
    print('hello')
```

however hitting `CTRL+C` while running this code just results in abrupt exit. no stack trace and no `hello` printed
```
import time
import quickfix

try:
    time.sleep(100)
finally:
    print('hello')
```

doing this appears to solve the issue:
```
import time
import signal

import quickfix
signal.signal(signal.SIGINT, signal.default_int_handler)

try:
    time.sleep(100)
finally:
    print('hello')
```

not entirely sure what is going on

**Comment by orenmnero** [comment]
Doesn't seem to be an issue anymore with the latest version in python3
