### ISSUE TITLE
x64 support and windows

### ISSUE THREAD

**Issue by leleftheriades** [quickfix/quickfix#227]
We would like to use x64 on windows, but we see that such a configuration is not supported.
There was a pull request from 1.5 years ago, but that is not compatible with the current version of the source code.

According to the old pull request, upgrading to x64 requires:
-**Adding some typedef** in Utility.h
#ifdef _MSC_VER
	typedef SOCKET socket_handle;
        #define INVALID_SOCKET_HANDLE INVALID_SOCKET
#else
	typedef int socket_handle;
        #define INVALID_SOCKET_HANDLE -1
#endif
-Changing the datatype of socket from **int** to **socket_handle** in 36 files
  HttpConnection.cpp
  HttpConnection.h
  HttpServer.cpp
  HttpServer.h
  SocketAcceptor.cpp
  SocketAcceptor.h
  SocketConnection.cpp
  SocketConnection.h
  SocketConnector.cpp
  SocketConnector.h
  SocketInitiator.cpp
  SocketInitiator.h
  SocketMonitor.cpp
  SocketMonitor.h
  SocketServer.cpp
  SocketServer.h
  ThreadedSocketAcceptor.cpp
  ThreadedSocketAcceptor.h
  ThreadedSocketConnection.cpp
  ThreadedSocketConnection.h
  ThreadedSocketInitiator.cpp
  ThreadedSocketInitiator.h
  Utility.cpp
  Utility.h
  ThreadedSSLSocketAcceptor.cpp
  ThreadedSSLSocketAcceptor.h
  ThreadedSSLSocketConnection.cpp
  ThreadedSSLSocketConnection.h
  ThreadedSSLSocketInitiator.cpp
  ThreadedSSLSocketInitiator.h
  SSLSocketAcceptor.cpp
  SSLSocketAcceptor.h
  SSLSocketConnection.cpp
  SSLSocketConnection.h
  SSLSocketInitiator.cpp
  SSLSocketInitiator.h

Are there any plans to add support for x64 builds?
Should I make the changes on my own and submit a pull request?

**Comment by karopawil** [comment]
I have been building x64 builds on Windows with cmake. Can give it a try.

**Comment by lefterise** [comment]
karopawil, the problem is that the SOCKET descriptor in a 64bit application is 64 bits. As it is now, socket descriptors in Quickfix are int (32 bit). If I just build without changing the datatype of socket, I am vulnerable because if given a socket descriptor by the operating system that does not fit in 32bits, my application will misbehave.

**Comment by karopawil** [comment]
To be absolutely on the safe side it is better to do what you suggest (opinion varies as to if this is required or not). Boost asio has something similar

#elif defined(BOOST_ASIO_WINDOWS) || defined(__CYGWIN__)
typedef SOCKET socket_type;

**Comment by leleftheriades** [comment]
I tried to change the datatype of socket, but hit a brick wall on OpenSSL. BIO_new_socket takes int as the socket parameter. The comment in OpenSSL about this is:

Even though sizeof(SOCKET) is 8, it's safe to cast it to int, because
the value constitutes an index in per-process table of limited size
and not a real pointer. And we also depend on fact that all processors
Windows run on happen to be two's-complement, which allows to
interchange INVALID_SOCKET and -1.

**Comment by leleftheriades** [comment]
closing this topic as it was merged to master
