### ISSUE TITLE
Segmentation fault on fix.TransactTime()

### ISSUE THREAD

**Issue by hootnot** [quickfix/quickfix#229]
Hi,

It seems that:

    ```
    >>> import quickfix as fix
    >>> print(fix.TransactTime())
    60=20190211-13:25:53
   ```
works fine, but:
```
    >>> import quickfix as fix
    >>> print(fix.TransactTime(1549891822))
    Segmentation fault (core dumped)
```

This is on ubuntu 16.04
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2

**Comment by dingobye** [comment]
Thank you for reporting this issue, Feite! There is a fix in #280
