### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gregschmit** [quickfix/quickfix#236]
I noticed that the last commit was last year in April (Apr 20, 2018). There are open issues and pull requests. Is this project dead?

**Comment by leleftheriades** [comment]
Any chance of merging "Improved compatibility with Windows x64" ?
We would like it if we don't have to maintain our own separate copy

**Comment by marlowa** [comment]
Seems dead to me. I forked a version which contains a fix for the deprecated/removed C++98 exception specifications. It still hasn't been adopted. This is going to make quickfix awkward for post C++98 compiler environments.

**Comment by leleftheriades** [comment]
marlowa I think that got merged

**Comment by quickfix** [comment]
Did you do a pull request? Doesn't this merged PR resolve the issue?

https://github.com/quickfix/quickfix/commit/dab6d9f937e3bc700a2e8be681936b0069857609

**Comment by mkst** [comment]
Bump... There are number of PRs that look good to merge...

**Comment by leleftheriades** [comment]
We are also a bit concerned about the slow merges, perhaps the author is busy with other projects

**Comment by quickfix** [comment]
This is it exactly. My role at Cumberland has kept me quite busy. I’ll try to set aside some time to review PRs and merge some stuff in next week.

**Comment by marlowa** [comment]
I am pleased to see there have been quite a few merges recently. That's great. But I haven't yet seen any announcement about a planned release.
