### ISSUE TITLE
Impossible to capture NewOrderSingle from my FIX client

### ISSUE THREAD

**Issue by Jambon1510** [quickfix/quickfix#238]
I am not able to record/capture the NewOrderSingle message from my FIX client 

I am currently coding a fix validator which embed a fix client able to send orders.
When sending an order I would need to record/capture the NewOrderSingle message from the toApp function but except the session ID I don't receive anything from this fuction (fromApp function is working fine and I receive anything I need) . I can however receive the NewOrderSingle (35=D) in the log file so it means somehow client is able to get it.

```python
def toApp(self, sessionID, message):
        print("Sending the following message: %s" % message.toString())
        self.add_message_in_stack(message)
        return
``` 
I am therefore expecting to get the FIX message in FIX client within toApp method or any other method which will allow me to save the exact message contain

example: 
```
8=FIX.4.2|9=214|35=D|34=8|49=TEST|52=20190404-07:37:06.000|56=CLIENT|1=ACCOUNT|11=251|15=JPY|21=1|22=4|38=200|40=5|48=JP3890350006|49=VALIDATOR|54=1|55=8316|57=BROKER_ID|59=0|109=TEST|115=TEST|116=TEST|207=JT|10=117|
```

**Comment by yosqueoy** [comment]
toApp signiture is not `toApp(self, sessionID, message)`, but `def toApp(self, message, sessionID)`?
http://www.quickfixengine.org/quickfix/doc/html/application.html

**Comment by Jambon1510** [comment]
Indeed, not sure why I ended up with inverting those 2 variables.
Thx a lot yosqueoy
