### ISSUE TITLE
How to parse fix protocal message in python3 ?

### ISSUE THREAD

**Issue by ReasonExplore** [quickfix/quickfix#248]
Hi ,I am using fix protocal client with python3, and I meet a problem with high concurrency,when the server(write by C++) push message to me, i can just parse the message by single thread  to a string,then use the threadpool to improve the processing power, but it can not follow the server because the single thread parse message, But when I try to parse the message by threadpool or other memcache or multiprocess,it always thow me a Segment Fault, Could you help me?
how to parse the fix message with concurrent in python3?  Thanks a lot!

**Comment by ReasonExplore** [comment]
![image](https://user-images.githubusercontent.com/48011584/59649293-b64ab180-91b4-11e9-8f59-9f7187bc6202.png)
and this is my code

**Comment by yosqueoy** [comment]
How about Message constructors? https://github.com/quickfix/quickfix/blob/master/src/C%2B%2B/Message.h

```python
copy_of_message = quickfix.Message(str(message))
```
Or
```python
copy_of_message = quickfix.Message(message)
```

Perhaps python's deepcopy is not deep enough for C++ data references.

**Comment by ReasonExplore** [comment]
@yosqueoy ，It works! thank you very much!

**Comment by ReasonExplore** [comment]
> How about Message constructors? https://github.com/quickfix/quickfix/blob/master/src/C%2B%2B/Message.h
> 
> ```python
> copy_of_message = quickfix.Message(str(message))
> ```
> 
> Or
> 
> ```python
> copy_of_message = quickfix.Message(message)
> ```
> 
> Perhaps python's deepcopy is not deep enough for C++ data references.

@yosqueoy ，hi yosqueoy，sorry for trouble you again, because I meet anothor question by using  copy_of_message = quickfix.Message(message) this method; fix protocal is singel thread, so I must use this code in a single thread, but this code cost some times(sometimes one message cost 0.02s), I Recive the message and  run this code then put this to queue, the bottleneck of my client process power is in this code, do you have an idea for this?

**Comment by ReasonExplore** [comment]
> > How about Message constructors? https://github.com/quickfix/quickfix/blob/master/src/C%2B%2B/Message.h
> > ```python
> > copy_of_message = quickfix.Message(str(message))
> > ```
> > 
> > 
> > Or
> > ```python
> > copy_of_message = quickfix.Message(message)
> > ```
> > 
> > 
> > Perhaps python's deepcopy is not deep enough for C++ data references.
> 
> @yosqueoy ，hi yosqueoy，sorry for trouble you again, because I meet anothor question by using copy_of_message = quickfix.Message(message) this method; fix protocal is singel thread, so I must use this code in a single thread, but this code cost some times(sometimes one message cost 0.02s), I Recive the message and run this code then put this to queue, the bottleneck of my client process power is in this code, do you have an idea for this?

I use `trans_message = message.toString()` then put it to queue,and I will `fix.message(msg)` at my threadpool, it works;
but when I use `message.getGroup(i, md_entries_group)` parse the group, I meet the error:
*** quickfix.FieldNotFound: Field not found
any suggestions? thanks

**Comment by ReasonExplore** [comment]
> > > How about Message constructors? https://github.com/quickfix/quickfix/blob/master/src/C%2B%2B/Message.h
> > > ```python
> > > copy_of_message = quickfix.Message(str(message))
> > > ```
> > > 
> > > 
> > > Or
> > > ```python
> > > copy_of_message = quickfix.Message(message)
> > > ```
> > > 
> > > 
> > > Perhaps python's deepcopy is not deep enough for C++ data references.
> > 
> > 
> > @yosqueoy ，hi yosqueoy，sorry for trouble you again, because I meet anothor question by using copy_of_message = quickfix.Message(message) this method; fix protocal is singel thread, so I must use this code in a single thread, but this code cost some times(sometimes one message cost 0.02s), I Recive the message and run this code then put this to queue, the bottleneck of my client process power is in this code, do you have an idea for this?
> 
> I use `trans_message = message.toString()` then put it to queue,and I will `fix.message(msg)` at my threadpool, it works;
> but when I use `message.getGroup(i, md_entries_group)` parse the group, I meet the error:
> *** quickfix.FieldNotFound: Field not found
> any suggestions? thanks

I found a way to solve this question, this error because the DataDictionary is not in it origin sequence, I use the `    message = fix.Message()
    dataDictionary = fix.DataDictionary("./spec/FIX44.xml")
    message.setString(msg_string, True, dataDictionary)` to set the string to message struct object,then parse it is ok;
and this action allow me to use my queue and threadpool to process the message, meet the need of quickly recive and process message, thank you anyway!
