### ISSUE TITLE
[bug] ValidateFields not working with UseDataDictionary=N

### ISSUE THREAD

**Issue by sarritesh** [quickfix/quickfix#252]
Hi I am using quickfix engine version 1.14.3 , in spite of having ValidateFieldsHaveValue=N message with empty tags are getting rejected. Note that in my case UseDataDictionary=N, 
Is there a way to resolve this in config ? Do we know which all quickfix engine is impacted with this bug ? Bug that i am pointing seems to be exactly represented as mentioned in below link.

https://github.com/connamara/quickfixn/issues/464

**Comment by orenmnero** [comment]
#482 

I wrote unit and acceptance tests for the latest version in master and at least now this seems to work. If this is still and issue please provide more details with message logs so we can replicate.
