### ISSUE TITLE
Question: server response on SecurityListRequest

### ISSUE THREAD

**Issue by travek** [quickfix/quickfix#262]
Hello!

I'm trying to get from the server response on SecurityListRequest. I'm sending request without issues and I'm getting answer from the server. When it comes to QuickFix client I receive and issue: Tag not Identified for this message type.

What is wrong and what should I check to properly process SecurityList incoming message ??

(8=FIX.4.4☺9=1950☺35=y☺34=4☺49=ROSX-MD-UAT☺52=20190827-12:10:19.117☺56=PUBLISH
ER_QUOTE-MT-UAT☺146=47☺55=AUD/CHF☺11001=0.0001☺11002=0.000001☺55=AUD/JPY☺11001=0
.0001☺11002=0.000001☺55=AUD/NZD☺11001=0.0001☺11002=0.000001☺55=AUD/RUB_TOM☺11001
=0.01☺11002=0.0001☺55=AUD/USD☺11001=0.0001☺11002=0.000001☺55=BKT/RUB☺11001=0.01☺
11002=0.0001☺55=CAD/JPY☺11001=0.0001☺11002=0.000001☺55=CHF/JPY☺11001=0.0001☺1100
2=0.000001☺55=CNH/RUB_TOM☺11001=0.0001☺11002=0.000001☺55=DJI/USD☺11001=0.0001☺11
002=0.000001☺55=EUR/AUD☺11001=0.0001☺11002=0.000001☺55=EUR/CAD☺11001=0.0001☺1100
2=0.000001☺55=EUR/CHF☺11001=0.0001☺11002=0.000001☺55=EUR/GBP☺11001=0.0001☺11002=
0.000001☺55=EUR/JPY☺11001=0.0001☺11002=0.000001☺55=EUR/RUB☺11001=0.01☺11002=0.00
01☺55=EUR/RUB_TOD☺11001=0.01☺11002=0.0001☺55=EUR/RUB_TOM☺11001=0.01☺11002=0.0001
☺55=EUR/SEK☺11001=0.0001☺11002=0.000001☺55=EUR/USD☺11001=0.0001☺11002=0.000001☺5
5=EUR/USD_TOD☺11001=0.0001☺11002=0.000001☺55=EUR_TODTOM☺11001=0.0001☺11002=0.000
001☺55=GBP/AUD☺11001=0.0001☺11002=0.000001☺55=GBP/CAD☺11001=0.0001☺11002=0.00000
1☺55=GBP/CHF☺11001=0.0001☺11002=0.000001☺55=GBP/JPY☺11001=0.0001☺11002=0.000001☺
55=GBP/USD☺11001=0.0001☺11002=0.000001☺55=JPY/RUB_TOD☺11001=0.01☺11002=0.0001☺55
=NZD/USD☺11001=0.0001☺11002=0.000001☺55=USD/CAD☺11001=0.0001☺11002=0.000001☺55=U
SD/CHF☺11001=0.0001☺11002=0.000001☺55=USD/CNH☺11001=0.0001☺11002=0.000001☺55=USD
/CNY☺11001=0.0001☺11002=0.000001☺55=USD/JPY☺11001=0.01☺11002=0.0001☺55=USD/RUB☺1
1001=0.01☺11002=0.0001☺55=USD/RUB_DEC☺11001=0.0001☺11002=0.000001☺55=USD/RUB_JUN
☺11001=0.0001☺11002=0.000001☺55=USD/RUB_MAR☺11001=0.0001☺11002=0.000001☺55=USD/R
UB_SEP☺11001=0.0001☺11002=0.000001☺55=USD/RUB_TOD☺11001=0.01☺11002=0.0001☺55=USD
/RUB_TOM☺11001=0.01☺11002=0.0001☺55=USD/RUB_TOM3M☺11001=0.0001☺11002=0.000001☺55
=USD/TRY☺11001=0.0001☺11002=0.000001☺55=USD_TODTOM☺11001=0.01☺11002=0.0001☺55=XA
G/USD☺11001=0.0001☺11002=0.000001☺55=XAU/USD☺11001=0.0001☺11002=0.000001☺55=ZAR/
RUB☺11001=0.0001☺11002=0.000001☺320=1☺322=1☺560=0☺10=156☺)
Action: <20190827-12:11:24.709000000, FIX.4.4:PUBLISHER_QUOTE-MT-UAT->ROSX-MD-UA
T, event>
(Message 4 Rejected: Tag not defined for this message type:55)
<20190827-12:11:24.717000000, FIX.4.4:PUBLISHER_QUOTE-MT-UAT->ROSX-MD-UAT, outgo
ing>
(8=FIX.4.4☺9=141☺35=3☺34=5☺49=PUBLISHER_QUOTE-MT-UAT☺52=20190827-12:11:24.717☺
56=ROSX-MD-UAT☺45=4☺58=Tag not defined for this message type☺371=55☺372=y☺373=2☺
10=124☺)

**Comment by quickfix** [comment]
You likely have not provided a DataDictionary file. A DataDictionary is
necessary to parse messages with repeating groups.

**Comment by xiaohua439912875** [comment]
I've provided the Datadictionary file, but no duplicate groups have been read

**Comment by iscaswang** [comment]
1、First ensure you provide DataDictionary setting to FIX44.xml
2、Second，check the receiver is using the standard fix44 protocol. For 'Tag not Identified for this message type', it usually means that certain field that should be interpreted in group interrupted due to the field unknown.  In that case, you should ask your receiver for their modified protocol spec file, or you can check the data from receiver and manually parse each field again standard FIX44.xml to check which field cause the error.
