### ISSUE TITLE
invalid field ' -DHAVE_SSL=ON' when running cmake

### ISSUE THREAD

**Issue by FabioNevesRezende** [quickfix/quickfix#264]
Cmake version: **3.13.3**
CmakeOutput.log:

> The system is: Windows - 10.0.17134 - AMD64

steps to reproduce:

Download the repo:

`git clone https://github.com/quickfix/quickfix`

try to build it:

`cmake  -DHAVE_SSL=ON -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:PATH="..\install" -DOPENSSL_ROOT_DIR="C:\libraries_C17\include" ..\build`

expected result:
To generate the VS 2017 files to build

what happened:

> 
> CMake Error at CMakeLists.txt:13 (project):
>   Generator
> 
>     Visual Studio 15 2017 Win64
> 
>   given toolset specification
> 
>      -DHAVE_SSL=ON
> 
>   that contains invalid field ' -DHAVE_SSL=ON'.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/fabio.rezende/Desktop/quickfix/build/CMakeFiles/CMakeOutput.log".
>

**Comment by karopawil** [comment]
Can you try after changing the order

cmake -G "Visual Studio 15 2017 Win64"  -DHAVE_SSL=ON -DCMAKE_INSTALL_PREFIX:PATH="..\install" -DOPENSSL_ROOT_DIR="C:\libraries_C17\include" ..\build

**Comment by FabioNevesRezende** [comment]
same error...

**Comment by karopawil** [comment]
I am not on windows, but on ubuntu this works for me:

~/Downloads/cmake-3.15.2-Linux-x86_64/bin/cmake  -DHAVE_SSL=ON -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="install-path" -DOPENSSL_ROOT_DIR="path to openssl" ..

-- The CXX compiler identification is GNU 7.4.0
-- The C compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Project name quickfix
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdio.h
-- Looking for include file stdio.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - found
-- Checking prototype gethostbyname_r for HAVE_GETHOSTBYNAME_R_3_ARG - False
-- Checking prototype gethostbyname_r for HAVE_GETHOSTBYNAME_R_5_ARG - False
-- Checking prototype gethostbyname_r for HAVE_GETHOSTBYNAME_R_6_ARG - True
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")  
-- OPENSSL_INCLUDE_DIR: /usr/include
-- OPENSSL_LIBRARIES: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- OPENSSL_ROOT_DIR: path to openssl
-- Building with SSL
-- Checking for shared ptr.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- set HAVE_STD_SHARED_PTR
-- Checking for unique ptr.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_UNIQUE_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_UNIQUE_PTR_IN_STD_NAMESPACE - Success
-- Found unique in std namespace using <memory> header.
-- set HAVE_STD_UNIQUE_PTR
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nkoak/github-stuff/quickfix/build

**Comment by FabioNevesRezende** [comment]
just to be sure, the "DOPENSSL_ROOT_DIR" must point to the `include` dir, right?

**Comment by karopawil** [comment]
let's say you installed something like (https://stackoverflow.com/questions/16248775/cmake-not-able-to-find-openssl-library)

ssl header is here   -- > /usr/local/ssl/include/openssl/
ssl library is here  -- > /usr/local/ssl/lib/libssl.a
                          /usr/local/ssl/lib/libcrypto.a

Then,
 -DOPENSSL_ROOT_DIR=/usr/local/ssl

**Comment by FabioNevesRezende** [comment]
Sure, the problem was that I was referencing a wrong directory for the `DOPENSSL_ROOT_DIR`, now cmake run successfully
