### ISSUE TITLE
Any plans on removing all the deprecated C++98 stuff?

### ISSUE THREAD

**Issue by rigtorp** [quickfix/quickfix#273]

**Comment by leleftheriades** [comment]
be specific

**Comment by rigtorp** [comment]
`throws()`, `auto_ptr<>` etc.

**Comment by leleftheriades** [comment]
They have been hidden behind pragmas. You can choose to disable them. Removing them completly will break compatibility

**Comment by rigtorp** [comment]
Isn't it time to move to C++11? RedHat 7, SUSE, other current enterprise LTS distros comes with C++11 compilers.

**Comment by Ambal** [comment]
@rigtorp , C++11, C++14 or C++17?

**Comment by leleftheriades** [comment]
You can't really make this decision on their behalf, legacy software may make use of some out of support library, that must be built under a certain compiler. Since C++ has no ABI they are stuck with it.

**Comment by rigtorp** [comment]
@leleftheriades Legacy systems can still use legacy releases. The ABI is defined by the compilers + std library combination + quickfix exported symbols. 

@Ambal C++11 since it's now very ubiquitous on production enterprise platforms.

**Comment by Ambal** [comment]
@rigtorp , it makes total sense to move at least to C++11 but quickfix owners must warn about deprecation of C98 in future releases.

**Comment by orenmnero** [comment]
on master auto_ptr is gone, throws removed when compiling with C++17
