### ISSUE TITLE
Which OpenSSL version is the right one to build this project?

### ISSUE THREAD

**Issue by FabioNevesRezende** [quickfix/quickfix#278]
So, the [last issue I opened here](https://github.com/quickfix/quickfix/issues/267) was caused because I was trying to build with a very old version of OpenSSL which generated that giant list of errors. Then, I've tried with the most recent version of the lib and it solved a lot of errors but one remain also related to Openssl, so my question is, which version exactly will have all the includes necessary to build quickfix? Steps to reproduce:

- Download the latest version of openssl to windows [here ](https://www.openssl.org/source/openssl-1.1.1d.tar.gz) and unpack it (in my case, in Desktop)
- Download this project

```
    git clone https://github.com/quickfix/quickfix.git
    cd quickfix
```

- run cmake pointing to the includes of the openssl lib:

```
     cmake . -DHAVE_SSL=1 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\fabio.rezende\Desktop\quickfix\install" -DOPENSSL_ROOT_DIR="C:\Users\fabio.rezende\Desktop\openssl-1.1.1d.tar\openssl-1.1.1d\openssl-1.1.1d\include"
```

Open the `quickfix.sln` VS project in Visual Studio 2017 and `Build Solution` , the build process fails with the following:

>Error	C1083	Cannot open include file: 'openssl/opensslconf.h': No such file or directory	quickfix	

There's also the files **quickfix_vs12.sln quickfix_vs14.sln quickfix_vs15.sln** in project root but these doesn't contain SSL code flags (`#ifdef HAVE_SSL`) activated (that's why I can build them) but I need the ssl option. I've read in [SO](https://stackoverflow.com/a/49317129) that this problem can be actually just a linking problem of Visual Studio, if that's the case, then how can I proceed here? Thanks

**Comment by leleftheriades** [comment]
try building openssl yourself. It will generate that file.
You will need: Perl (I used strawberry) and Nasm (Netwide Assembler)

I use the `no-shared` parameter to build with static C++ runtime (MT). If you prefer the C++ run-time to be from a dll (MD) omit that parameter.

I use the `VC-WIN64A` to build it as x64. You can use `VC-WIN32` to build as x86

```
git clone -b OpenSSL_1_1_1d --depth 1 https://github.com/openssl/openssl openssl

perl --version
nasm --version

perl Configure VC-WIN64A no-shared  --openssldir="%CD%"\rel64 --prefix="%CD%"\rel64
Nmake
nmake install

Nmake distclean
perl Configure VC-WIN64A no-shared   --debug  --openssldir="%CD%"\dbg64 --prefix="%CD%"\dbg64
nmake install
```

**Comment by FabioNevesRezende** [comment]
Building openssl in windows fails too (lol, I love windows)

`C:\Users\fabio.rezende\Desktop\openssl\openssl\e_os.h(13): fatal error C1083: Não é possível abrir arquivo incluir: 'limits.h': No such file or directory`

When running the first `nmake` command

**Comment by leleftheriades** [comment]
Sorry I forgot to mention these commands must be run from within 
x64 Native Tools Command Prompt for VS 2019
or
x86 Native Tools Command Prompt for VS 2019
