### ISSUE TITLE
installation for python3 on macOS Catalina

### ISSUE THREAD

**Issue by cutterbuck** [quickfix/quickfix#281]
I am trying to install quickfix for python3 on macOS Catalina, but I keep getting a slew of errors.

(https://github.com/quickfix/quickfix/files/3726186/python3_quickfix_error.docx)

The error log is attached in the link above. Any idea why this might be happening? I'm desperate to find a fix and migrate my project to Python3 given that it will be deprecated very soon. Many thanks for any suggestions.

**Comment by cutterbuck** [comment]
Actually the problem seems to be with python3.7+ on macOS Catalina. The quickfix build works with any version of python from 3.6 and older.

**Comment by dendisuhubdy** [comment]
Confirming this

**Comment by deep0892** [comment]
Facing the same issue, pip install quickfix unable to install lib. This seems like a similar issue to this. 
[](https://github.com/pandas-dev/pandas/issues/23424)

**Comment by deep0892** [comment]
https://github.com/pandas-dev/pandas/issues/23424
