### ISSUE TITLE
How to static link with quickfix on linux

### ISSUE THREAD

**Issue by smartseal** [quickfix/quickfix#282]
Hi, 
On linux, after I build and make install quickfix, there are only dynamic library .so files and there is no libquickfix.a generate.

How can I build and static link with libquickfix.a?

**Comment by smartseal** [comment]
I can't find libquickfix.a file in /usr/local/lib. There are only libquickfix.so link and files

**Comment by dendisuhubdy** [comment]
Change the build settings on CMakeLists.txt @smartseal from `shared` to `static`
