### ISSUE TITLE
Quickfix 1.15.1 python3 SocketAcceptor not logging in when UseDataDictionary=Y

### ISSUE THREAD

**Issue by psmcgrath** [quickfix/quickfix#287]
Issue in title- when the UseDataDictionary=Y using the normal FIX42.xml datadictionary, the socket accepter does not log into the session.  However, when UseDataDictionary=N, isLoggedIn returns true and the session is able to proceed as expected. This issue was not seen for me with 1.14.3 and python2, but I am upgrading.  Any advice/thoughts would be hugely appreciated.

**Comment by yosqueoy** [comment]
I don't have the same issue with v1.15.1, using Python 3.7. I set up one acceptor and one initiator with UseDataDictionary=Y (default), which had no issue to log in.

>the socket accepter does not log into the session. 

You mean **initiator** does not log into the session? Acceptor never tries to log into a session, but it accepts login requests from initiators.

**Comment by psmcgrath** [comment]
Yeah I guess the acceptor is never logged onto a session, e.g. when I have UseDataDictionary=N and i call isLoggedOn, i get true. When i have UseDataDictionary=Y and I call isLoggedOn, I get false.  Very very confusing to me
