### ISSUE TITLE
make check fails on setMessageOrder

### ISSUE THREAD

**Issue by jartu** [quickfix/quickfix#288]
Using the standard installation procedure, the following commands all succeeded:
```
./bootstrap
./configure
make
```
... but then `make check` fails and the contents of the test/test-suite.log is the following:

> `==========================================`
> QuickFIX 1.14.3: test/test-suite.log
> `==========================================`
> 
> \# TOTAL: 1
> \# PASS:  0
> \# SKIP:  0
> \# XFAIL: 0
> \# FAIL:  1
> \# XPASS: 0
> \# ERROR: 0
> 
> .. contents:: :depth: 2
> 
> `FAIL: check.sh`
> `==============`
> 
> `<ut>`
> `  <output>`
> `C++/test/FieldMapTestCase.cpp:37: error: Failure in setMessageOrder: Unhandled exception: Crash!`
> `FAILURE: 1 out of 409 tests failed (1 failures).`
> `Test time: 17.81 seconds.`
> `  </output>`
> `</ut>`
> `./runut.sh: line 1: kill: (-17590) - No such process`
> `FAIL check.sh (exit status: 1)`

**Comment by smitvora1904** [comment]
How you solved it?
