### ISSUE TITLE
Provide name to value mapping in DataDictionary

### ISSUE THREAD

**Issue by stevenlunt** [quickfix/quickfix#295]
This change will allow callers to do the inverse lookup to getValueName.

In DataDictionary.h:

1.	Add this line at the end of void addValueName( int field, const std::string& value, const std::string& name ):

  m_nameValues[std::make_pair(field, name)] = value;

2.	Add this method after that:

  bool getValueValue( int field, const std::string& name, std::string& value ) const
  {
      ValueToName::const_iterator i = m_nameValues.find(std::make_pair(field, name));
      if (m_nameValues.end() == i) return false;
      value = i->second;
      return true;
  }

3.	Add this member at the bottom:

  ValueToName m_nameValues;

**Comment by sourcedelica** [comment]
What about naming the new method `getNameValue()`?  That would be more consistent, matching the names of the parameters and the intention of the 

For example:
```
void addValueName( int field, const std::string& value, const std::string& name );
bool getValueName( int field, const std::string& value, std::string& name ) const;
bool getNameValue( int field, const std::string& name, std::string& value ) const;   // The new method
```

**Comment by stevenlunt** [comment]
Yeah, that does make sense


________________________________
On: 01 February 2020 14:50,
"Eric Pederson" <notifications@github.com<mailto:notifications@github.com>> wrote:


What about naming the new method getNameValue()? That would be more consistent, matching the names of the parameters and the intention of the

For example:

void addValueName( int field, const std::string& value, const std::string& name );
bool getValueName( int field, const std::string& value, std::string& name ) const;
bool getNameValue( int field, const std::string& name, std::string& value ) const;   // The new method


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_quickfix_quickfix_issues_295-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAHL7YHN3L6R4HZEZZUW4SJTRAXG65A5CNFSM4KOMMWT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKRFF2A-23issuecomment-2D581063400&d=DwMCaQ&c=sA0VaJZJFLZREu2pbPeqjXHJ-Wd9NNzgHW3gpUOLSSk&r=zVOrXXhfqt2WGs65ZflFDaqDSQbNoJUrRC6PiADZ0sU&m=2rGFY9ajprPMFhXnpqYt7hVVSRWS-Bc4FGktwFKbBD4&s=5lZmi4Q1efwIxUkHeJsnyTFqUPpur_XITkSEl_gd4uk&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHL7YHPPNNDAYS3Z3POT7FLRAXG65ANCNFSM4KOMMWTQ&d=DwMCaQ&c=sA0VaJZJFLZREu2pbPeqjXHJ-Wd9NNzgHW3gpUOLSSk&r=zVOrXXhfqt2WGs65ZflFDaqDSQbNoJUrRC6PiADZ0sU&m=2rGFY9ajprPMFhXnpqYt7hVVSRWS-Bc4FGktwFKbBD4&s=WsHzsHen6rJImNEwS0PsXEqe8ube7x5fCT4glpbjWes&e=>.

________________________________________________________________________

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

Tradeweb reserves the right to monitor and review the content of all messages sent to or from this e-mail address. Messages sent to or from this e-mail address may be stored on the Tradeweb e-mail system.
