### ISSUE TITLE
LNK2019 VS19

### ISSUE THREAD

**Issue by Ivans1310** [quickfix/quickfix#299]
I copied the include folder and the quickfix.lib file to the directory of my project  and I added its new paths in the additional inclusion directories and additional library directories correspondingly. And I added the library name in the linker input.
All this in VS2019
Compiling this code I get those errors.

`	LNK2019	external symbol "public: __cdecl FIX::SessionSettings::SessionSettings(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (??0SessionSettings@FIX@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z) unresolved referred to in the  main function 	FixClient	C:\dev\FixClient\client.obj	1	
`

`
Error	LNK1120	1 unresolved external FixClient	C:\dev\FixClient\x64\Debug\FixClient.exe	1	
`

```
#include "quickfix/Session.h"
#include <quickfix/SessionSettings.h>
#include "Application.h"
#include <iostream>

int main(int argc, char** argv)
{
    try
    {
        if (argc < 2) return 1;
 
        std::string fileName = "config.txt";

        FIX::SessionSettings settings(fileName);//  Line error

        Application application;
        return 0;
    }
    catch (std::exception & e)
    {
        std::cout << e.what();
        return 1;
    }
}
```
Thanks for your time, I hope that anyone be able guide me to fix this error.

**Comment by leleftheriades** [comment]
did you compile quickfix for 64 bit?

**Comment by Ivans1310** [comment]
Thank you very much for your timely response.
I had make sure that compile my project with its correspondingly binarie file, I compiled the binarie 32 bit with the debugger of 32 bit and the binarie 64 bit with the debugger of 64bit. 

The SettingsSession instantiation was resolved that error disappeared but  now in both scenarios I am getting these errors.
The compiled code is the same.
Do you have any idea? Thanks.

`1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_accept referenced in function "unsigned __int64 __cdecl FIX::socket_accept(unsigned __int64)" (?socket_accept@FIX@@YA_K_K@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_bind referenced in function "int __cdecl FIX::socket_bind(unsigned __int64,char const *,int)" (?socket_bind@FIX@@YAH_KPEBDH@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_closesocket referenced in function "void __cdecl FIX::socket_close(unsigned __int64)" (?socket_close@FIX@@YAX_K@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_connect referenced in function "int __cdecl FIX::socket_connect(unsigned __int64,char const *,int)" (?socket_connect@FIX@@YAH_KPEBDH@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_ioctlsocket referenced in function "bool __cdecl FIX::socket_fionread(unsigned __int64,int &)" (?socket_fionread@FIX@@YA_N_KAEAH@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_getpeername referenced in function "char const * __cdecl FIX::socket_peername(unsigned __int64)" (?socket_peername@FIX@@YAPEBD_K@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_getsockname referenced in function "short __cdecl FIX::socket_hostport(unsigned __int64)" (?socket_hostport@FIX@@YAF_K@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_getsockopt referenced in function "int __cdecl FIX::socket_getsockopt(unsigned __int64,int,int &)" (?socket_getsockopt@FIX@@YAH_KHAEAH@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_htons referenced in function "int __cdecl FIX::socket_bind(unsigned __int64,char const *,int)" (?socket_bind@FIX@@YAH_KPEBDH@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_inet_addr referenced in function "int __cdecl FIX::socket_bind(unsigned __int64,char const *,int)" (?socket_bind@FIX@@YAH_KPEBDH@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_inet_ntoa referenced in function "char const * __cdecl FIX::socket_hostname(unsigned __int64)" (?socket_hostname@FIX@@YAPEBD_K@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_listen referenced in function "unsigned __int64 __cdecl FIX::socket_createAcceptor(int,bool)" (?socket_createAcceptor@FIX@@YA_KH_N@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_ntohs referenced in function "short __cdecl FIX::socket_hostport(unsigned __int64)" (?socket_hostport@FIX@@YAF_K@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_recv referenced in function "int __cdecl FIX::socket_recv(unsigned __int64,char *,unsigned __int64)" (?socket_recv@FIX@@YAH_KPEAD0@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_send referenced in function "int __cdecl FIX::socket_send(unsigned __int64,char const *,unsigned __int64)" (?socket_send@FIX@@YAH_KPEBD0@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_setsockopt referenced in function "int __cdecl FIX::socket_setsockopt(unsigned __int64,int,int)" (?socket_setsockopt@FIX@@YAH_KHH@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_shutdown referenced in function "void __cdecl FIX::socket_close(unsigned __int64)" (?socket_close@FIX@@YAX_K@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_socket referenced in function "unsigned __int64 __cdecl FIX::socket_createAcceptor(int,bool)" (?socket_createAcceptor@FIX@@YA_KH_N@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_gethostbyname referenced in function "char const * __cdecl FIX::socket_hostname(char const *)" (?socket_hostname@FIX@@YAPEBDPEBD@Z)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_WSAStartup referenced in function "void __cdecl FIX::socket_init(void)" (?socket_init@FIX@@YAXXZ)
1>quickfix.lib(Utility.obj) : error LNK2019: unresolved external symbol __imp_WSACleanup referenced in function "void __cdecl FIX::socket_term(void)" (?socket_term@FIX@@YAXXZ)
1>C:\dev\FixClient\x64\Debug\FixClient.exe : fatal error LNK1120: 21 unresolved externals`

**Comment by lefterise** [comment]
link with ws2_32.lib

**Comment by Ivans1310** [comment]
> link with ws2_32.lib

thank you very much! it is working.
