### ISSUE TITLE
Need a way to stop/disconnect session - any attempted way  crashes the instance

### ISSUE THREAD

**Issue by Zaytsev11B** [quickfix/quickfix#300]
I’ve tried many different ways how to logout/stop FIX session but quckfix instance always crashes with this stack - logout/disconnect/unregister:

#0  0x00007f339e948337 in raise () from /lib64/libc.so.6
#1  0x00007f339e949a28 in abort () from /lib64/libc.so.6
#2  0x000000000042700a in sig_fatal_cb(int, siginfo_t*, void*) ()
#3  <signal handler called>
#4  0x0000000000000000 in ?? ()
#5  0x00007f339f5f794a in goacc_destroy_thread (data=0x7f3308000fe0) at ../.././libgomp/oacc-init.c:359
#6  0x00007f339f80dc62 in __nptl_deallocate_tsd () from /lib64/libpthread.so.0
#7  0x00007f339f80de73 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f339ea1088d in clone () from /lib64/libc.so.6

What I have discovered from gdb, this thread was created by quick fix for incoming sessions.

(gdb) info threads
  Id   Target Id         Frame 
  15   Thread 0x7f3329b9c700 (LWP 30474) 0x00007f339f813afb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
  14   Thread 0x7f33137fe700 (LWP 30478) 0x00007f339ea10e63 in epoll_wait () from /lib64/libc.so.6
  13   Thread 0x7f3393888700 (LWP 30466) 0x00007f339f8119f5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  12   Thread 0x7f3333fff700 (LWP 30470) 0x00007f339f8119f5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  11   Thread 0x7f332a39d700 (LWP 30473) 0x00007f339ea10e63 in epoll_wait () from /lib64/libc.so.6
  10   Thread 0x7f332939b700 (LWP 30475) 0x00007f339f813afb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
  9    Thread 0x7f3391bff700 (LWP 30469) 0x00007f339ea10e63 in epoll_wait () from /lib64/libc.so.6
  8    Thread 0x7f332ab9e700 (LWP 30472) 0x00007f339f8119f5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  7    Thread 0x7f3392886700 (LWP 30468) 0x00007f339ea10e63 in epoll_wait () from /lib64/libc.so.6
  6    Thread 0x7f3394089700 (LWP 30465) 0x00007f339f8119f5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7f33a2f05bc0 (LWP 30464) 0x00007f339ea10e63 in epoll_wait () from /lib64/libc.so.6
  4    Thread 0x7f3393087700 (LWP 30467) 0x00007f339f811da2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3    Thread 0x7f3313fff700 (LWP 30477) 0x00007f339ea10e63 in epoll_wait () from /lib64/libc.so.6
  2    Thread 0x7f3328b9a700 (LWP 30476) 0x00007f339f80efd7 in pthread_join () from /lib64/libpthread.so.0
* 1    Thread 0x7f3312ffd700 (LWP 30479) 0x00007f339e948337 in raise () from /lib64/libc.so.6

02/07 16:03:55.970559 [0x00007f3312ffd700] [DEBUG] Liquidity Provider added: 40111 — this is a log from logon method.

Here is an example: I’ve used session logout(), disconnect() and unregisterSession(). All crashed with the same stack.

if (fixEngineInitiator->isLoggedOn()) {
    for (const auto& sessionID: fixEngineInitiator->getSessions()) {
        auto* session = FIX::Session::lookupSession(sessionID);
        if (session->isLoggedOn()) {
            //1 session->logout();
            //2 session->unregisterSession(sessionID);
            //3 session->disconnect();
        }
    }
}

**Comment by leleftheriades** [comment]
can you try doing it from a different thread?

**Comment by Zaytsev11B** [comment]
Thanks!
