### ISSUE TITLE
FIX  5.0 sp2 Missing Message Types

### ISSUE THREAD

**Issue by pmarcellino** [quickfix/quickfix#302]
I think this is an issue. I found that the FIX  5.0 sp2 is missing some message types, at least 0 through 5, which are in earlier specs and should be in this one.

**Comment by mkst** [comment]
> With the release of FIX Protocol Version 5.0 the session layer specification was separated from the application layer specification (aka Transport Independence). “FIXT” is the label used to identify the separate session layer specification and to identify the FIX Session version being used.

[src](https://www.fixtrading.org/standards/fixt/)

Therefore you'll find those messages [here](https://github.com/quickfix/quickfix/blob/master/spec/FIXT11.xml).

**Comment by pmarcellino** [comment]
Thank you very much for your reply. This has solved my issue, which was actually just a lack of knowledge.
