### ISSUE TITLE
Getting High Latency, when receiving data

### ISSUE THREAD

**Issue by xhimanshuz** [quickfix/quickfix#307]
Hi, Currently working on High-Frequency Trading Application for Fix Protocol, I'm using quick-fix C++, But getting too much latency, like 30-35 milliseconds on my server having specs Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Is there any way to make in in less than 5 microseconds. Like retrieving data and processing it to onMessage should be < 5 micros.

**Comment by karopawil** [comment]
Depending on whether you are using a file or DB there is always an overhead of saving messages and updating session number, plus context switches. I doubt if you can get 5 micros latency with quickfix.

**Comment by Ambal** [comment]
Hi, @xhimanshuz . You should configure quickfix to use MemoryStore as message storage for maximum performance. But quickfix is not really a low latency solution. You might want to try something like fix8 if you really need to got to less than 5 micros.

**Comment by Malacarne** [comment]
> Hi, @xhimanshuz . You should configure quickfix to use MemoryStore as message storage for maximum performance. But quickfix is not a low latency solution. You might want to try something like fix8 if you really need to go down to less than 5 micros.

Are there any plans to integrate quickfix with Redis?

**Comment by Ambal** [comment]
hi, @Malacarne . I'm not aware of any plans. You are free to write your own wrapper for this DB engine and submit it via a pull request. The MessageStore interface is very simple.

**Comment by Malacarne** [comment]
> 
> 
> hi, @Malacarne . I'm not aware of any plans. You are free to write your own wrapper for this DB engine and submit it via a pull request. The MessageStore interface is very simple.

Thank you for your reply, @Ambal. I've already integrated Redis in my quickfix C++ app. However, I'm using a third party library ([redox](https://github.com/hmartiro/redox), based on [hiredis](https://github.com/redis/hiredis)). But I'm not sure if it's possible to "integrate" those third party libs in a pull request in quickfix ...

**Comment by karopawil** [comment]
@Malacarne What could be done is a conditional compile. A user who wants to use it can enable the compile flags and supply the required 3rd party lib herself. This is what is done for OpenSSL for example.

**Comment by xhimanshuz** [comment]
Now It is getting 19-21 microseconds, Sorry maybe I tested on debug mode. and thanks @Ambal your suggestion decreased 9-10 microseconds it is really appreciating.
