### ISSUE TITLE
Out-of-tree build doesn't work

### ISSUE THREAD

**Issue by Bu11etmagnet** [quickfix/quickfix#317]
```
$ git clone https://github.com/quickfix/quickfix.git
$ cd quickfix
$ ./bootstrap
$ mkdir _build
$ cd _build
$ ../configure
$ make
make  all-recursive
make[1]: Entering directory '~/quickfix/_build'
Making all in UnitTest++
/bin/bash: line 20: cd: UnitTest++: No such file or directory
Makefile:504: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '~/quickfix/_build'
Makefile:413: recipe for target 'all' failed
make: *** [all] Error 2
```
The build system assumes that `configure` has been run in the quickfix directory. This is unnecessarily restrictive.

**Comment by orenmnero** [comment]
Report it to autoconf, but I doubt you'll get far, it's explicitly stated as the first requirements in their instructions.

> cd to the directory containing the package's source code and type `./configure' to configure the package for your system. If you're using csh on an old version of System V, you might need to type `sh ./configure' instead to prevent csh from trying to execute configure itself. Running configure takes awhile. While running, it prints some messages telling which features it is checking for.

https://www.math.utah.edu/docs/info/autoconf_10.html
