### ISSUE TITLE
ssize_t redefinition

### ISSUE THREAD

**Issue by sergey-chernikov** [quickfix/quickfix#321]
Hi there!
I've encountered build error (ssize_t redefinition with different type) when building QuickFIX sources on Windows 64-bit (VS2017) and when some other includes are used in the project, too (e.g. libbtc in my case). Though this patch seems to fix the issue:
>--- a/src/C++/Utility.h
+++ b/src/C++/Utility.h
@@ -69,7 +69,7 @@
 #include <direct.h>
 #include <time.h>
 typedef int socklen_t;
-typedef int ssize_t;
+typedef LONG_PTR ssize_t;
 typedef SOCKET socket_handle;

I.e. when using the same type that is pre-defined somewhere in Windows headers.

**Comment by orenmnero** [comment]
#474
