### ISSUE TITLE
How to run a python demo ? 

### ISSUE THREAD

**Issue by pzg250** [quickfix/quickfix#325]
Hi, 
I am beginner of the quickfix. Just want to know how to run the python demo. 
Do I need to build the package first ?  Or just pip install .
I think there should be a fix config file in demo project. What does the file looks like? And where to put it?
I just see the executor.py in sample folder. But don't know how to run it. 

Any help is appreciated. Thanks in advance. 

Regards,

**Comment by cpollio83** [comment]
Did you figure this out?  Pip install quickfix doesn't work for me either

**Comment by minikiller** [comment]
pls find some example in github, there are many example for quickfix python.

**Comment by pzg250** [comment]
@minikiller got it.
Let me close this.

**Comment by minikiller** [comment]
https://github.com/abhi-g80/pytradesimulator this example is very great. @pzg250  if you have face same problem just like me in this issue https://github.com/abhi-g80/pytradesimulator/issues/2,pls let me know! thanks!

**Comment by pzg250** [comment]
> https://github.com/abhi-g80/pytradesimulator this example is very great. @pzg250 if you have face same problem just like me in this issue [abhi-g80/pytradesimulator#2](https://github.com/abhi-g80/pytradesimulator/issues/2) let me know! thanks!

Great! Thanks very much!
