### ISSUE TITLE
(C++) How to NOT use the session/XXX.seqnums file?

### ISSUE THREAD

**Issue by kenjichanhkg** [quickfix/quickfix#326]
I'm facing a problem with the C++ version of the library. I store the sending seq no in a database, and when my program startup, it needs to recover missed messages at that exact the seq no in DB, from DropCopy/FIX gateway.

I don't care about the sending seq at all, but I need to specify the sending seq instead of relying on the .seqnums file.

Is there a way I can specify the seq no in code when I intitialize the client?
The other way I can think of is to modify the .seqnums manually by code everytime before I init the client.

Could anyone help me please?

Thanks,
Kenji Chan

**Comment by orenmnero** [comment]
You can use one of the provided MessageStores for various databases, or implement your own class using the MessageStore interface.
