### ISSUE TITLE
Columns beginstring, sendercompid and targetcompid should probably be nullable in table event_log

### ISSUE THREAD

**Issue by vkapartzianis** [quickfix/quickfix#329]
All SQL code that creates the `event_log` table doesn't allow nulls in columns `beginstring`, `sendercompid` and `targetcompid`, as far as I can tell. SQL Server code, for example:

https://github.com/quickfix/quickfix/blob/85bb8a9acae6b0e6a2c37d498e646a5437f23983/src/sql/mssql/quickfix_database.sql#L28-L37

DB log classes try and write `NULL` values to those columns, when events aren't session-related, though. OdbcLog for example:

https://github.com/quickfix/quickfix/blob/85bb8a9acae6b0e6a2c37d498e646a5437f23983/src/C%2B%2B/OdbcLog.cpp#L228-L242

In practice, connections, SSL handshakes, etc. are silently missing from the event log in the DB.

I worked around this on SQL Server by executing the following. Is there any better way to resolve the issue?

``` SQL
ALTER TABLE event_log ALTER COLUMN beginstring CHAR(8);
ALTER TABLE event_log ALTER COLUMN sendercompid VARCHAR(64);
ALTER TABLE event_log ALTER COLUMN targetcompid VARCHAR(64);
```

**Comment by orenmnero** [comment]
#459
