### ISSUE TITLE
Detecting version in c++

### ISSUE THREAD

**Issue by sashkab** [quickfix/quickfix#333]
It appears that quickfix version is not available in any c++ header files. What is the proper way to detect version of the QuickFix engine from c++ code? 

For example, in v1.14.0 you [renamed FIX::Dictionary::get/setLong into FIX::Dictionary::get/setInt](https://github.com/quickfix/quickfix/commit/3b0782bcbaf696be2a3d6ca8d8971c33e0c5ec9d), but I need to keep my application compatible with both of v1.13.3 and v.1.14.3. 

Thanks.

**Comment by orenmnero** [comment]
There is a #define in config.h

#define PACKAGE_VERISON "1.15.1"

**Comment by sashkab** [comment]
I don't see it, @orenmnero 

```sh
$ git describe
v1.15.1-164-g5a71e253
$ git grep PACKAGE_VERISON
$ find . -name config.h
./src/C++/config.h
$ grep VERSION ./src/C++/config.h
$ grep VERSION ./src/C++/config*
$
```
