### ISSUE TITLE
quickfix current git version does not compile on Visual Studio 2019 because of missing poll.h

### ISSUE THREAD

**Issue by mteske** [quickfix/quickfix#334]
I did 
mkdir build
cd build
cmake ..
cmake --build .

and get
C:\cygwin64\home\michael.teske\build\thirdparty\unchanged\quickfix\testquickfix-1.16.0\src\C++\SocketMonitor.h(43): fatal error C1083: Cannot open include file: 'poll.h': No such file or directory

This is easily fixable by putting poll.h in the #else branch of #ifdef _MSCVER, but then it fails in src/C++/HttpConnection.cpp, which now unconditionally requires poll (and not only the header), which is not available on windows.

**Comment by mteske** [comment]
I could get it to work with an own simple poll.h header:
$ cat src/C++/poll.h
#ifdef _MSC_VER
#ifndef MSC_POLL
#include <winsock2.h>
inline int  poll(
  LPWSAPOLLFD fdArray,
  ULONG       fds,
  INT         timeout
) {return WSAPoll(fdArray, fds, timeout);}
#define MSC_POLL 1
#endif
#endif


I don't know if this will work on linux, though.

**Comment by mteske** [comment]
additionally, I fixed some compiler errors like this:
diff -ur orig-quickfix-1.16.0/src/C++/SocketMonitor.cpp testquickfix-1.16.0/src/C++/SocketMonitor.cpp
--- orig-quickfix-1.16.0/src/C++/SocketMonitor.cpp      2020-10-19 16:16:20.728502900 +0200
+++ testquickfix-1.16.0/src/C++/SocketMonitor.cpp       2020-10-21 09:24:00.414124900 +0200
@@ -178,7 +178,7 @@
   int pfds_size = m_readSockets.size() +
                   m_connectSockets.size() +
                   m_writeSockets.size();
-  struct pollfd pfds[ pfds_size ];
+  struct pollfd pfds[ 1024 ];
   buildSet( m_readSockets, pfds, POLLPRI | POLLIN );
   buildSet( m_connectSockets, pfds + m_readSockets.size(), POLLOUT | POLLERR );
   buildSet( m_writeSockets, pfds + m_readSockets.size() + m_connectSockets.size(),
@@ -222,7 +222,7 @@
   }
 }

-void SocketMonitor::processWrite( Strategy& strategy, socket_handle socket_fd )
+void SocketMonitor::processWrite( Strategy& strategy, int socket_fd )
 {
   socket_handle s = socket_fd;
   if( m_connectSockets.find(s) != m_connectSockets.end() )



And I had to manually copy over config.h and Except.h (and of course poll.h) to include/quickfix to be able to compile the examples. This makes me wonder if anyone is using the current quickfix version on windows at all or if I miss something fundamentally...

**Comment by vrnhgd** [comment]
I am having the same issues. Not sure how this wasn't an issue before given that the relevant pull to [switch from select() to poll()](https://github.com/quickfix/quickfix/pull/210) is pretty old.

Appreciate your post though, hopefully it'll help others build locally while we figure out if this is intentional

**Comment by vrnhgd** [comment]
@mteske looks like @orenmnero merged in that pull req on September 24th. My guess is that anybody using quickfix from windows hasn't fetched upstream changes since at least then

**Comment by vrnhgd** [comment]
build succeeds if you revert: `git revert -m 1 5a0a38185f670481820fc88213d5cc963adf90eb`

**Comment by mteske** [comment]
looks like this has been fixed an all reverted to select
