### ISSUE TITLE
Session disconnect crashes

### ISSUE THREAD

**Issue by ageorgallides** [quickfix/quickfix#346]
Two different threads are trying to access the SocketMonitor::m_connectSockets member and the application crashes.

Our thread calls the Session::reset() in order to disconnect the session

**Callstack:**
SocketMonitor::drop()
SSLSocketConnection::disconnect()
Session::disconnect()
Session::reset()

At the same time, the Quickfix thread started from Initiator

**Callstack:**
SocketMonitor::block()
SocketConnector::block()
SSLSocketInitiator::onStart()
Initiator::startThread()

What is the recommended way of disconnecting a session?

**Comment by orenmnero** [comment]
A call stack would be helpful. Please open a new issue with more details if you have them.

**Comment by leleftheriades** [comment]
but a call stack was included here. it shows session.reset() which is called from his own thread, eventually calls monitor.drop() which accesses m_connectSockets. at the same time the quickfix thread calls SocketMonitor::block() which also accesses the same variable.
