### ISSUE TITLE
NextExpectedMsgSeqnum tag (789) in Logon message

### ISSUE THREAD

**Issue by paggigithub** [quickfix/quickfix#347]
NextExpectedMsgSeqnum (789) in Logon message for FIX5.0 SP2 is not going through, and i don't see the implementation as well.

**Comment by tfmark** [comment]
You probably have to add custom logic in the `toAdmin` method. I had to do this for Username/Password which I expected to be standard...

**Comment by qiuhaha** [comment]
> You probably have to add custom logic in the `toAdmin` method. I had to do this for Username/Password which I expected to be standard...
I guest it is the price of supporting across FIX4.0 ~ FIX5.0 with just one code base...
