### ISSUE TITLE
session: insertSendingTime() showMilliseconds is not set correctly

### ISSUE THREAD

**Issue by dgoulet** [quickfix/quickfix#348]
I was attempting to find out why the `TransactTime` of an `ExecutionReport` had its milliseconds but the `SendingTime` had not. In the FIX logs, I can see that the milliseconds are there but then when it ends up in the application, it is set to 0.

My investigation brought me to `Session::insertSendingTime()` which has this clear wrong string comparison:

```
  if( m_sessionID.getBeginString() == BeginString_FIXT11 )
    showMilliseconds = true;
  else
    showMilliseconds = m_sessionID.getBeginString() >= BeginString_FIX42;
```

First part of the if/else if fine but second part is not. I'm using FIX 4.4 and this `>=` comparison will always yield `false` except if FIX4.2 is used and thus resulting in never having milliseconds for the `SendingTime`.

(Same goes for `insertOrigSendingTime()`)

I'm not familiar enough to propose a fix here but I'm guessing

**Comment by orenmnero** [comment]
Hi David,

I'm not sure I'm seeing what is wrong here. I ran the acceptance tests for
FIX4.4 and verified that milliseconds are being appended to the SendingTime
field.

The code as written was difficult to unit test, so I extracted the logic
and wrote a unit test that verifies for each supported BeginString.

I created a pull request. This pull request does not change the logic, it
just extracts it so it is unit testable. I'd appreciate it if you can
review it and let me know if I'm missing something.

https://github.com/quickfix/quickfix/pull/349/files

**Comment by dgoulet** [comment]
Oh my apologies, my testing was using constant "strings" instead of the C++ `string` and so the comparison ofc was always false. Thus, the code is right.

However, it doesn't solve my mystery of the `SendingTime` having its milliseconds always to 0. Take this message (from the logs), this is from the exchange to my application. (Note that the exchange here is a Python framework I built using QuickFIX 1.15.1 bindings).

```
[...] 52=20210224-13:55:16.809 [...]
```

And that value once back into the application (client side) results in: `2021-02-24 13:55:16.000` using this code to format it for PostgresSQL insertion:

```
  int year, month, day, hour, minute, second, millis;
  ostringstream oss;

  ts.getYMD(year, month, day);
  ts.getHMS(hour, minute, second, millis);

  oss << year << "-"
      << std::setfill('0') << setw(2) << month << "-"
      << std::setfill('0') << setw(2) << day << " "
      << std::setfill('0') << setw(2) << hour << ":"
      << std::setfill('0') << setw(2) << minute << ":"
      << std::setfill('0') << setw(2) << second << "."
      << std::setfill('0') << setw(3) << millis;
  return oss.str();
```

The `millis` is always 0. I've also checked with the `getString()` on the `FIX::SendingTime` object and it results in:

> 2021-02-24 13:55:16.000

So somewhere somehow, the milliseconds are getting shaved off but I can't figure out where. If you could simply indicate me a place in the code I could do the checks where the binary->object conversion is happening for `UtcTimeStamp`, I could trace what is happening.

As for the PR, it does look good to me. Test pass.

Thanks!

**Comment by orenmnero** [comment]
Hi David,

I tried to replicate this but was unsuccessful.

I'll point you to the relevant code, so maybe you can trace through it.

The conversion happens in the UtcTimeStampConvertor linked below, along
with the relevant test cases. Please let me know if you figure out what is
happening.

https://github.com/quickfix/quickfix/blob/master/src/C++/FieldConvertors.h#L466-L542
https://github.com/quickfix/quickfix/blob/master/src/C++/test/FieldConvertorsTestCase.cpp#L275-L365

**Comment by dgoulet** [comment]
Thanks! So the `convert()` function you pointed at seems to be doing its job. I traced it and it indeed parses properly the milliseconds from the FIX message.

I can also see the field being extracted properly in `Message()` object but still, in my `crack()` for an `ExecutionReport`, the `SendingTime`, which up to that point seems to contain the milliseconds, has them set to 0 and its length is 17 flat (not 21 with milliseconds).

I tracked it down to I believe one callsite which I'm a bit stuck after.

In my `onMessage(const FIX44::ExecutionReport& msg, const FIX::SessionID& sessionID)`, doing this very simple dumb print yields two results:

```
void onMessage(const FIX44::ExecutionReport& msg, const FIX::SessionID& sessionID)
{
  cerr << "MSG: " << msg << endl;

  FIX::SendingTime st;
  msg.getFieldIfSet(st);    
  std::cerr << "st string: " << st.getString() << endl;
}
```

Results in:
> MSG: [...] 52=20210226-14:37:23.413 [...]

versus

> st string: 20210226-14:37:23

I'm baffled how the `getFieldIfSet()` could change things since both string output seems to be using the same underlying function to get the string values. I will try to dig deeper in the meantime once I have more time. Thanks.

**Comment by rd888** [comment]
Hi David,
I have noticed the same. I am using quickfix via python (quickfix-1.15.1-cp37-cp37m-win_amd64.whl). All the 52/SendingTime tags are sent out without milliseconds. By overwriting the value of the field in toAdmin()/toApp(), I get the millisecond to be set.
header.setField(fix.StringField(52, datetime.utcnow().strftime("%Y%m%d-%H:%M:%S.%f")[:-3]))
I also notice that neither MillisecondsInTimeStamp=Y nor TimeStampPrecision=3 in the configuration settings had any effect on the outgoing 52/Sendingtime tag.
Richard

**Comment by orenmnero** [comment]
You are pulling from the wrong place. SendingTime is a header field. You need to do

msg.getHeader().getFieldIfSet(st);

Also the isSet methods return booleans, make sure to check the result. If you check it you will see it is returning false.

The time you are getting is the default value which is the current time without milliseconds as the lowest common denominator between fix versions.
