### ISSUE TITLE
tradeclient doesn't send TargetCompID on Logon

### ISSUE THREAD

**Issue by nappa85** [quickfix/quickfix#351]
I'm trying tradeclient to debug a server I wrote, but every logon attempt fails because it's missing field TargetCompID (56).
This is an example of a Logon I'm receiving:
```8=FIX.4.2\u{1}9=75\u{1}35=A\u{1}34=430\u{1}49=CLIENT1\u{1}52=20210309-16:18:54.53744```
My tradeclient.cfg is untouched, except for `SocketConnectHost` and `SocketConnectPort`.

**Comment by nappa85** [comment]
Yes, I know, and the message is sent by tradeclient, that is part of this repository.
Isn't it a bug?

**Comment by nappa85** [comment]
Nevermind, I found out the problem, buffer was truncated before message end, in facts my example wasn't 75 bytes long

**Comment by quickfix** [comment]
Oh I see. Yes it sounds like it. I have to confirm if I can replicate on my
side.

**Comment by orenmnero** [comment]
Oh I missed this before I responded to your other message. Glad you figured
it out.
