### ISSUE TITLE
Cannot write on database (mysql5 or 8) with python3.8 on windows10

### ISSUE THREAD

**Issue by Dbergesio** [quickfix/quickfix#352]
Hello,

I've installed quickfix using .whl module from https://www.lfd.uci.edu/~gohlke/pythonlibs/#quickfix cause via `pip install` it was not possible. I even _unsuccesfully_ tried to use what I found in this official github repo (installing the C++ version or converting into python-equivalent via swig).
Anyway, I was able to make quickfix working using the downloaded package: the client connects to a simple server I have, it exchanges FIX messages, it writes logs; but it **does not write on mysql database** (I tried with mysql5 and 8 database, too). And neither the prompt nor the python console prints any error not warnings about database connections. I am sure the .cfg file is all read since I get what it is written within via python's commands.

I started thinking my configuration file is missing one line, or something should be set off to write on database and not on log file (for instance, if it writes on a .log file it does not upload entries on the database, and viceversa. Could it be?).

Here the client's .cfg file I'm using:
```
[DEFAULT]
DefaultApplVerID=FIX.4.4
ConnectionType=initiator
FileLogPath=./Logs/
StartTime=00:00:00
EndTime=00:00:00
UseDataDictionary=Y
ReconnectInterval=60
LogoutTimeout=5
LogonTimeout=30
ResetOnLogon=Y
ResetOnLogout=Y
ResetOnDisconnect=Y
SendRedundantResendRequests=Y
SocketNodelay=N
ValidateUserDefinedFields=N
ValidateFieldsOutOfOrder=N
MySQLStoreDatabase=quickfix
MySQLStoreUser=user1
MySQLStorePassword=pass1
MySQLStoreHost=1.2.3.4
MySQLStorePort=5
MySQLLogDatabase=quickfix
MySQLLogUser=user1
MySQLLogPassword=pass1
MySQLLogHost=1.2.3.4
MySQLLogPort=5
MySQLLogIncomingTable=messages_log
MySQLLogOutgoingTable=messages_log
MySQLLogEventTable=event_log

[SESSION]
BeginString=FIX.4.4
SenderCompID=CLIENT1
TargetCompID=TEST_SERVER
HeartBtInt=30
SocketConnectPort=10032
SocketConnectHost=acceptor
DataDictionary=./spec/FIX44.xml
FileStorePath=./Sessions/
```

I would like to check within the .pyd library python imports - where I think database writing should be done - but it's not readable and I'm therefore stuck.

Any clues?

Thank you very much.

**Comment by booboothefool** [comment]
i'm also stuck on this. were you able to get it to work?

**Comment by Dbergesio** [comment]
Hi,
well, I spent time to make it myself. And since I had no clues I tried to get what was done for C++ and translate it to Python. It was not an easy task, at start.
Start checking in quickfix/src/C++/

**Comment by orenmnero** [comment]
Python API does not currently support the mysql store or log. We may add this soon.
