### ISSUE TITLE
Acceptor::poll does not respect timeout

### ISSUE THREAD

**Issue by robambalu** [quickfix/quickfix#355]
It looks like calling poll will disregard the timeout argument completely.  It ends up getting the timeout value from this method:

`inline timeval* SocketMonitor::getTimeval( bool poll, double timeout )
{
  if ( poll )
  {
    m_timeval.tv_sec = 0;
    m_timeval.tv_usec = 0;
    return &m_timeval;
  }
`

This is completely unexpected and confusing.  Either poll should respect the timeout, or it should not take timeout as an argument.
As it stands now it looks like there is no way to block for a specific amount of time

**Comment by orenmnero** [comment]
#448
