### ISSUE TITLE
readFromStream unit test failure?

### ISSUE THREAD

**Issue by falloutphil** [quickfix/quickfix#359]
Hi,

Build head of master:
https://github.com/quickfix/quickfix/commit/741e96dbc89988b76ac63e8b036ffac8dcf2bf5c

I'm running Guix 1.3 over Ubuntu 18.04.  I'm doing:
cmake
make

I add the following cmake switches (removing the CXX one doesn't make a differnce):
"-DHAVE_SSL=ON -DCMAKE_CXX_STANDARD=17"

So far everything is fine.

Then running inside the source/test folder:
./check.sh

I get a single failure in the unit tests (all the acceptance tests pass):

<ut>
  <output>
/tmp/guix-build-quickfix-1.16.drv-0/source/src/C++/test/DataDictionaryTestCase.cpp:858: error: Failure in readFromStream: Unhandled exception: Configuration failed: Could not parse data dictionary stream
FAILURE: 1 out of 412 tests failed (1 failures).
Test time: 18.06 seconds.
  </output>
</ut>

The issue seems to be with the passing of fstream, rather than locating FIX43.xml - I note other tests are sucessfully finding and using the FIX xml files under spec directory.

Any ideas what the problem might be or how to diagnose further?

name: openssl
version: 1.1.1j

name: gcc-toolchain
version: 7.5.0

name: cmake
version: 3.19.2

All the tests seem to pass if I build using cmake directly from Ubuntu rather than using Guix packages manager over Ubuntu.

**Comment by orenmnero** [comment]
Don't know anything about GUIX or why using it would change the results of the build.
