### ISSUE TITLE
Dynamic acceptor sessions in quickfix?

### ISSUE THREAD

**Issue by falconair** [quickfix/quickfix#363]
Is there a way to get around having to define sessions in a configuration file?

I’d like to write simple Python code which accepts any incoming session, and decides on its validity during runtime.

Another potential use case is that session information is created during runtime, rather than via a static file.

**Comment by orenmnero** [comment]
We do not, but there is a PR under review that supports this.

**Comment by Avarice91** [comment]
Hi any update on this?
