### ISSUE TITLE
Datatype for tag 1009 (SideLastQty)

### ISSUE THREAD

**Issue by FilippoTanganelli** [quickfix/quickfix#364]
Currently datatype for tag 1009 is "INT" but it should be "QTY" (float).

https://fiximate.fixtrading.org/en/FIX.Latest_EP266/tag1009.html

Is there a reason why it is still "INT" in QuickFIX?
I'm having problem with latest Deutsche Borse FIX LF protocol and I had to create a custom tag as a workaround.

**Comment by orenmnero** [comment]
#494
