### ISSUE TITLE
TimestampPrecision key is not working

### ISSUE THREAD

**Issue by lijielile** [quickfix/quickfix#365]
From the link http://www.quickfixengine.org/quickfix/doc/html/configuration.html
TimestampPrecision: Used to set the fractional part of timestamp. Allowable values are 0 to 9. If set, overrrides MillisecondsInTimeStamp.

But not matter what value I set, it seems this key is not working at all. The timestamp always has the same format. Plus it is not overriding the MillisecondsInTimeStamp key. Anybody knows how to make it work?

**Comment by lijielile** [comment]
Does anybody know in which version of quickfix is this key added?

**Comment by quickfix** [comment]
Are you using a specific version of the latest from github?

**Comment by lijielile** [comment]
The version I use is 1.5. But I also tried the newest version. None of them works.

**Comment by lijielile** [comment]
Ah, I see the problem. I use QuickFIX/N and it doesn't have this key. Is QuickFIX/N different to this?

**Comment by orenmnero** [comment]
Ah yes, QuickFIX/N is maintained by Connamara. They try to replicate the
features of the main project but sometimes things get missed.

You can contact them by various means listed here:
http://quickfixn.org/help/

You can check with them to see if they can add support for this feature.
