### ISSUE TITLE
FileStore::open(): Can we include errno and strerror(errno) when fail to open file throws ConfigError?

### ISSUE THREAD

**Issue by kevinarpe** [quickfix/quickfix#366]
Hello,

From here: https://github.com/quickfix/quickfix/blob/master/src/C%2B%2B/FileStore.cpp#L102

I noticed that we do not include errno and strerror(errno). This would be helpful to debug filesystem issues.

Something like this would help:

```
#include <cstring>  // for char* std::strerror(int)

if ( !m_msgFile )
{
    const int e = errno;  // Save state into local temp var to be safe
    throw ConfigError( "Could not open body file: " + m_msgFileName
        + " (Error: " + std::to_string(e) + std::string(": ") + std::strerror(e)
        + std::string(")");
}

```
That logic could be nicely wrapped in a helper function to be called when failing to open any file.

**Comment by orenmnero** [comment]
#478
