### ISSUE TITLE
`make check` Configuration failed: Unable to connect to database [MySQL server has gone away]

### ISSUE THREAD

**Issue by EricLifelab** [quickfix/quickfix#367]
Hello,

Compiling the QuickFix 1.14.3 under Ubuntu 18.04 with `./configure --with-python3 --with-mysql`. 

Had set up the mysql database with `create.sh mysql` without errors. 

The error attached as below in the test-suite.log: 
[test-suite.log](https://github.com/quickfix/quickfix/files/6952043/test-suite.log)

Thanks.

**Comment by orenmnero** [comment]
This means you have a mysql connectivity issue. Consult the mysql documentation for more information.
