### ISSUE TITLE
4 easy to eliminate warnings during compiling

### ISSUE THREAD

**Issue by shleym2000** [quickfix/quickfix#369]
Compiled by Visual Studio and got 4 warnings for 3 lines. All four make sense and should be easy to fix by, say, explicit conversion of the length into int ( static_cast<int>() )

1. quickfix\include\quickfix\FieldConvertors.h(355,1): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
2. quickfix\include\quickfix\FieldConvertors.h(355,1): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data
3. quickfix\include\quickfix\FieldConvertors.h(540,1): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
4. quickfix\include\quickfix\FieldConvertors.h(627,1): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

Warnings 1 and 2 are from different calls to the same method.

**Comment by orenmnero** [comment]
You didn't link to the PR, but I believe it was merged. Please confirm.
