### ISSUE TITLE
initiator.start() didn't trigger toAdmin 

### ISSUE THREAD

**Issue by josephchenhk** [quickfix/quickfix#371]
Hi all, I am trying to write an initiator. I couldn't get my snippet of login code work. **If I understand correctly, toAdmin function will be triggered after initiator.start(), and after sending credentials in toAdmin, we can successfully logon to the accepter, and trigger onLogon function.** However, my code never runs into the toAdmin block. Any advice?

Here is my client:

```
    try:
        settings = fix.SessionSettings(config_file)
        application = Application()
        storefactory = fix.FileStoreFactory(settings)
        logfactory = fix.FileLogFactory(settings)
        initiator = fix.SocketInitiator(application, storefactory, settings, logfactory)
        initiator.start()
        application.run()
        initiator.stop()
    except (fix.ConfigError, fix.RuntimeError) as e:
        print(e)
        initiator.stop()
        sys.exit()
```

And my application:

```
class Application(fix.Application):
    """FIX Application"""

    def toAdmin(self, message, sessionID):
        msgType = fix.MsgType()
        message.getHeader().getField(msgType)
        if (msgType.getValue() == fix.MsgType_Logon):
            print('Logging on.')
            message.setField(fix.Password('my_password'))
            message.setField(fix.Username('my_username'))
            message.setField(fix.ResetSeqNumFlag(True))
            fix.Session.sendToTarget(message, sessionID)
        return
```

**Comment by shamazkhan** [comment]
Hello @josephchenhk May i ask if you managed to find the solution to this issue? I am using FIX44 and experiencing the same issue. I am trying to pass Username/Password via toAdmin function, but it never goes through. Regards. Shamaz

**Comment by josephchenhk** [comment]
> Hello @josephchenhk May i ask if you managed to find the solution to this issue? I am using FIX44 and experiencing the same issue. I am trying to pass Username/Password via toAdmin function, but it never goes through. Regards. Shamaz

Hi @shamazkhan , unfortunately, I didn't manage to get it done. Hope somebody else reading the thread will give a solution:)

**Comment by shamazkhan** [comment]
@josephchenhk thanks for prompt response. May I ask you are using FIX44? I have observed that for fix43 or lower it seems to work.

**Comment by josephchenhk** [comment]
> @josephchenhk thanks for prompt response. May I ask you are using FIX44? I have observed that for fix43 or lower it seems to work.

Yes, I was using FIX44. Then it could probably be an issue for this release.

**Comment by orenmnero** [comment]
There isn't really enough information here. No indication if you connected or logging to indicate what quickfix was doing. Not much to go on unfortunately.
