### ISSUE TITLE
Does this support fix protocol 5.0 sp2 ?

### ISSUE THREAD

**Issue by coolboy95** [quickfix/quickfix#377]
I wish to know which protocols of fix api does C++ quickfix support .  Thanks

**Comment by alexpls** [comment]
Yep - quickfix supports FIX 5.0 SP2. The repo even includes a [dictionary](https://github.com/quickfix/quickfix/blob/master/spec/FIX50SP2.xml) for that version.

**Comment by coolboy95** [comment]
thanks alexpls
