### ISSUE TITLE
Cannot compile new QuickFix version in C++20

### ISSUE THREAD

**Issue by tellass567** [quickfix/quickfix#384]
Hello,
I have worked with a older version of QuickFix. Now I have updated my code to C++20 and installed the newest version of QuickFix. I have downloaded the code from https://github.com/quickfix/quickfix. Now I get compiler errors: FIX::FieldBase" has no member "first" 

This is the code that works with the old version of QuickFix, but not with the actual version:
```
const FIX::FieldMap& fieldMap
const FIX::DataDictionary* dataDictionary
...
for (auto itr = fieldMap.begin(), end = fieldMap.end(); itr != end; ++itr)
{
    dataDictionary->getFieldName(itr->first, fieldName);
}
...
```
The problem is the following line in FieldMap.h:
```
typedef std::vector < FieldBase, ALLOCATOR< FieldBase > > Fields;
```
This the a except from the old version:
```
typedef std::multimap < int, FieldBase, message_order, ALLOCATOR<std::pair<const int,FieldBase> > > Fields;
```

**Comment by leleftheriades** [comment]
According to git, 7 years ago the multimap was changed to vector.
instead of `itr->first` try using `itr->getTag()`
