### ISSUE TITLE
Python bindings getting stuck at quickfix.py:964/quickfix.py:906

### ISSUE THREAD

**Issue by esahione** [quickfix/quickfix#386]
Hi,

I'm using your Python bindings and intermittently the system gets stuck at that line. The only way I can see it is with py-spy -  with output:
`0.00%   0.00%   26.53s    26.61s   <lambda> (quickfix.py:964)`

or output:
`  0.00%   0.00%   12.28s    12.29s   <lambda> (quickfix.py:906)`

I didn't have this problem before moving to Linux (Arch); before that I was running a very similar system on Mac and I didn't see any issues.

Would you know what could be causing it or how I could debug it?

On the logs I see
```
20220216-22:41:44.968605000 : Socket Error: Connection reset by peer.
20220216-22:41:44.968620000 : Disconnecting
```

But the whole system is running on the same machine, with the QuickFix engine on both ends.

Cheers,
E

**Comment by orenmnero** [comment]
Not much to go on without a core file
