### ISSUE TITLE
DefaultApplVerID not defined in BusinessMessageReject's dictionary, maybe RefApplVerID ?

### ISSUE THREAD

**Issue by icelee123** [quickfix/quickfix#387]
https://github.com/quickfix/quickfix/blob/d73d1e86a2099d1dd6eaa3ed8b7d78ed73888877/src/C%2B%2B/Session.cpp#L930

8=FIXT.1.19=13835=334=33249=TEST912952=20220316-07:25:43.33856=MNCH45=39958=Tag not defined for this message type, field=1137371=1137372=j373=210=230

**Comment by orenmnero** [comment]
DefaultApplVerID is only valid on Logon messages

**Comment by icelee123** [comment]
the issure occurs when :

1. client sends an order message
2. server rejects the order and returns "BusinessMessageReject" which contains tag 1137 (DefaultApplVerID).
3. client raises an error since tag 1137 was not defined in BusinessMessageReject's xml dictionary file by default.

so maybe DefaultApplVerID should not be added to BusinessMessageReject?

code Session::generateBusinessReject



At 2023-07-19 10:23:47, "Oren Miller" ***@***.***> wrote:

DefaultApplVerID is only valid on Logon messages

**Comment by pblair-hartree** [comment]
Why is this issue closed? This issue causes Quickfix to send invalid BusinessMessageReject messages.
