### ISSUE TITLE
FIX50SP2 EP269

### ISSUE THREAD

**Issue by sylr** [quickfix/quickfix#389]
Would it be possible to update the [FIX50SP2.xml](https://github.com/quickfix/quickfix/blob/master/spec/FIX50SP2.xml) spec with the Expansion Pack 269 ?

Regards.

**Comment by icelee123** [comment]
maybe you need quickfixj-dictgenerator  in quickfixj
it can help you genenrate quickfix dict file (using fix official repository files)

**Comment by orenmnero** [comment]
#494
