### ISSUE TITLE
support ARM64?

### ISSUE THREAD

**Issue by justinweb** [quickfix/quickfix#395]
When I try to compile quickfix from source in ARM64 environment by using CMake, I got the following error messages:

/tmp/ccBckn7v.s: Assembler messages:
/tmp/ccBckn7v.s:10663: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:10664: Error: unknown mnemonic `xadd' -- `xadd x1,[x2]'
/tmp/ccBckn7v.s:10945: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:10946: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:16105: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:16106: Error: unknown mnemonic `xadd' -- `xadd x1,[x2]'
/tmp/ccBckn7v.s:28896: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:28897: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:29698: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:29699: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:53176: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:53177: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:53786: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:53787: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:54887: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:54888: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:72879: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:72880: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:79932: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:79933: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:80060: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:80061: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
/tmp/ccBckn7v.s:80558: Error: unknown mnemonic `lock' -- `lock'
/tmp/ccBckn7v.s:80559: Error: unknown mnemonic `xadd' -- `xadd x0,[x1]'
make[2]: *** [src/C++/CMakeFiles/quickfix.dir/build.make:76: src/C++/CMakeFiles/quickfix.dir/DataDictionary.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:518: src/C++/CMakeFiles/quickfix.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

After checking relative information, I found this problem had been raised an issue. However this issue seems still not solved.

Then I try to modify the AtomicCount.h (https://github.com/quickfix/quickfix/blob/master/src/C%2B%2B/AtomicCount.h) as  below:

```
#if defined(HAVE__ARM64OS)
#include <atomic>
#endif

#elif defined(HAVE__ARM64OS)

typedef std::atomic<long> atomic_count;

#else
```

My purpose is to use c++ standard atomic when my environment is ARM64.

About the preprocessor macro HAVE__ARM64OS, I added it in cmake_config.h.in.

```
#ifndef CONFIG_H_IN
#define CONFIG_H_IN

#cmakedefine HAVE_EMX
#cmakedefine HAVE_CXX17
#cmakedefine HAVE_STD_SHARED_PTR
#cmakedefine HAVE_SHARED_PTR_IN_TR1_NAMESPACE
#cmakedefine HAVE_STD_TR1_SHARED_PTR_FROM_TR1_MEMORY_HEADER
#cmakedefine HAVE_STD_UNIQUE_PTR

#cmakedefine HAVE_ARM64OS

#endif
```

After modifying those two files, I could successfully compile quickfix in my ARM64 environment.

cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHAVE_SSL=ON **-DHAVE_ARM64OS=ON** -DCMAKE_INSTALL_PREFIX:PATH="/usr/local" ..

I am not sure if this is the proper way to fix this problem. If anyone has a better way to fix it, please feel free to share it. Thanks.

**Comment by panosangelopoulos** [comment]
I fixed it by using a CFLAG, `CFLAGS "-march=armv8-a"` and then run the pip install command, 

In case you would like to try it in a docker world then something like that will do the trick

```
FROM python:3.9-alpine (Feel free to use any other version)

ENV CFLAGS "-march=armv8-a"

....
RUN pip install quickfix (or via the requirements file)
```

**Comment by orenmnero** [comment]
#430
