### ISSUE TITLE
Compatibility with Pypy

### ISSUE THREAD

**Issue by geokas7** [quickfix/quickfix#406]
I tried to install Quickfix under pypy with the following code:
pip3 install quickfix
The installation was failed.
The error contains the following error :

C++/QuickfixPython.cpp: In function ‘PyTypeObject* SwigPyPacked_TypeOnce()’:
      C++/QuickfixPython.cpp:2132:7: error: invalid conversion from ‘printfunc {aka int ()(_object, _IO_FILE, int)}’ to ‘Py_ssize_t {aka long int}’ [-fpermissive]

I would like to inform me if quickfix is compatible with pypy and if you could provide me a solution.

**Comment by michael-doubez** [comment]
I suspect this is due to an old swig generation.

**Comment by orenmnero** [comment]
Master has regenerated with a more recent version of swig
