### ISSUE TITLE
Compiling quickfix with C++20

### ISSUE THREAD

**Issue by flashnuke** [quickfix/quickfix#408]
I'm getting this error when compiling a project with quickfix and C++20:
`error: no template named 'auto_ptr' in namespace 'std'`
After some research it seems that the removal of `auto_ptr` in C++17 causes this, and by using the `HAVE_STD_UNIQUE_PTR` flag these errors should be dismissed (since `auto_ptr` will be replaced with `unique_ptr`)

when running `./configure` It shows me the following output:
```cmdline
checking for std::tr1::shared_ptr... no
checking for std::shared_ptr... yes
checking for boost::shared_ptr... yes
checking for std::unique_ptr... yes
checking for typeinfo in the global namespace... no
checking for typeinfo in the std namespace... yes
```

which indicates it should not compile with `auto_ptr` (I assume)

what am I doing wrong here?

edit:
On linux it compiles fine, only on macOS It throws these errors
It seems that `HAVE_STD_SHARED_PTR=ON` (printed it during the make process), and yet in this piece of code (`quickfix/wx/Utility.h`):
```c++
#if !defined(HAVE_STD_UNIQUE_PTR)
#define SmartPtr std::auto_ptr
#else
#include <memory>
#define SmartPtr std::unique_ptr
#endif
```
'HAVE_STD_UNIQUE_PTR' is undefined... thus attempting to use `auto_ptr` instead

**Comment by flashnuke** [comment]
Resolved by manually including in my project "config.h" which was generated when running Make command for quick fix (it has all the relevant macros defined)

**Comment by RoyalGoose** [comment]
> Resolved by manually including in my project "config.h" which was generated when running Make command for quick fix (it has all the relevant macros defined)

How you resolve it?
