### ISSUE TITLE
configure option -with-mysql=no does not work

### ISSUE THREAD

**Issue by mteske** [quickfix/quickfix#41]
When I give configure the option -with-mysql=no, libquickfix.so is still linked to libmysqlclient.so, although HAVE_MYSQL is correctly not defined in config.h. This is a working patch:
# Index: quickfix/m4/ax_lib_mysql.m4

--- quickfix/m4/ax_lib_mysql.m4 (Revision 71)
+++ quickfix/m4/ax_lib_mysql.m4 (Revision 72)
@@ -6,8 +6,6 @@

 AC_DEFUN([_MYSQL_CHECK],[
     AC_REQUIRE([_MYSQL_CONFIG])
-    MYSQL_CFLAGS=`$mysql_config --cflags`
-    MYSQL_LIBS=`$mysql_config --libs`
   AC_SUBST(MYSQL_CFLAGS)
   AC_SUBST(MYSQL_LIBS)
  ])
  @@ -30,6 +28,8 @@
   then
       AC_REQUIRE([_MYSQL_CHECK])
       AC_DEFINE(HAVE_MYSQL, 1, Define if you have sql library (-lmysqlclient))
-       MYSQL_CFLAGS=`$mysql_config --cflags`
-        MYSQL_LIBS=`$mysql_config --libs`
   fi
   AM_CONDITIONAL(HAVE_MYSQL, $has_mysql)
  ])

**Comment by orenmnero** [comment]
Fixed.
