### ISSUE TITLE
can only copy messages, can not move

### ISSUE THREAD

**Issue by danny-pav** [quickfix/quickfix#412]
We have 

class Message  ...
{
...
Message(const Message&);
...
};

why are there no move constructors or assignments?
i.e.
Message(Message&&);
Message& operator=(Message&&);

considering the objects used are mostly simple types (int, enum, etc) and std containers that already have move semantics (vector, map), this should be relatively simple to implement.  (The only type that my preliminary analysis shows to require non-trivial work is shared_array, but that too should not be hard to do.)

**Comment by Ambal** [comment]
Hi, @danny-pav . The answer is quite simple: the codebase is not updated to C++11 and later standards while CMake forces C++17. The FieldBase class, for example, also lacks move constructor/assignment operator

**Comment by danny-pav** [comment]
Would it be possible to add the appropriate functions (move construct, move assign) under the appropriate ifdef blocks (#ifdef (__cplusplus >= 201103L)) for a release?

**Comment by Ambal** [comment]
Hi, @danny-pav . I think the #ifdef block is not really required as this project cannot be compiled with C++03 compilers anymore - the C++11 is required at least in SocketConnectionTestCase.cpp (it uses std::unique_ptr<> directly)

**Comment by danny-pav** [comment]
is there any reason that move constructors / move assignment has not been added?  or is it simply inertia?

**Comment by orenmnero** [comment]
For quite some time new c++ features were not added to keep the code
compatible with older compilers still in use. I think we are way past that
now and can start taking advantage of more modern semantics.

**Comment by danny-pav** [comment]
@orenmnero For the work I am doing, the most important changes will be to 
ExecutionReport
OrderCancelReject
NewOrderSingle
NewOrderMultileg
OrderCancelReplaceRequest
MultilegOrderCancelReplace
OrderCancelRequest

I would need these changes in FIX44.

I would be amenable to entering a PR for these changes and once they are approved, to applying the analogous changes for the other versions of FIX and the remaining messages.

Would you be on board for this?
--Dan

**Comment by quickfix** [comment]
Those are generated with a code generator, we don’t update those files by
hand. The generator would need to be modified once, then it would be
applied to all messages automatically.

**Comment by danny-pav** [comment]
it looks to me like 
1. shared_array needs changes (add non trivial move copy, move assign), 
2. FIX FieldMap, Message, message_order need trivial move copy, move assign (use the "= default")
3. FIXnn messages require trivial move copy, move assign (use the "= default") -- this would be covered by the scripting.

**Comment by danny-pav** [comment]
additionally, i hope no one is using the code here: https://github.com/quickfix/quickfix/blob/d73d1e86a2099d1dd6eaa3ed8b7d78ed73888877/src/C%2B%2B/SharedArray.h#L169

as this looks like a bug in that m_pCtr is not initialized and i would be very concerned about using that.

**Comment by sweemer** [comment]
> For quite some time new c++ features were not added to keep the code compatible with older compilers still in use. I think we are way past that now and can start taking advantage of more modern semantics.

Hi, sorry to hijack this issue, but I just want to point out that the latest official release (v1.15.1) still does not compile as C++17 and above. Keeping the code compatible with older compilers still in use is important, but making the code compatible with newer compilers is also important and at this point C++17 is not even that new.

@orenmnero Could I ask you to please make a new release from the master branch as soon as you get the chance?

**Comment by daniel-und-pav-at-cargill-dot-com** [comment]
@sweemer - I think it is being conceded that newer compilers should be supported.  I am trying to get c++11 features supported.

**Comment by daniel-und-pav-at-cargill-dot-com** [comment]
@orenmnero I used my work identity to do some of the work: https://github.com/quickfix/quickfix/pull/413
next step will be to update the scriptable parts

**Comment by sweemer** [comment]
> I think it is being conceded that newer compilers should be supported. I am trying to get c++11 features supported.

That's a very worthwhile goal and I'm glad you're working on it. Note that the latest official release (v1.15.1) compiles as C++11 (and also as C++14) without error so those language versions are already "supported", though not to their full potential as you pointed out.

My goal is for the latest official release to successfully compile as C++17, regardless of what features the code uses. Again sorry for hijacking this issue but [previous issues](https://github.com/quickfix/quickfix/issues/368) have gone stale so I thought I'd raise it here while we have @orenmnero's attention.

**Comment by daniel-und-pav-at-cargill-dot-com** [comment]
@sweemer what does not compile for c++17?  Pretty sure we are using c++17 and 1.15.1 without modification.

**Comment by daniel-und-pav-at-cargill-dot-com** [comment]
@orenmnero I have made some changes locally to the scripts -- how do I run them to make sure they do what I intend them to do?

**Comment by sweemer** [comment]
> @sweemer what does not compile for c++17? Pretty sure we are using c++17 and 1.15.1 without modification.

Same problem reported in the issue I linked earlier:

```console
$ g++ --version
g++ (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0

$ cmake -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-std=c++17"

$ cmake --build build
[...]
/home/sweemer/quickfix-1.15.1/src/C++/FieldConvertors.h:201:3: error: ISO C++17 does not allow dynamic exception specifications
  201 |   throw( FieldConvertError )
      |   ^~~~~
```

**Comment by daniel-und-pav-at-cargill-dot-com** [comment]
> > @sweemer what does not compile for c++17? Pretty sure we are using c++17 and 1.15.1 without modification.
> 
> Same problem reported in the issue I linked earlier:
> 
> ```
> $ g++ --version
> g++ (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
> 
> $ cmake -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-std=c++17"
> 
> $ cmake --build build
> [...]
> /home/sweemer/quickfix-1.15.1/src/C++/FieldConvertors.h:201:3: error: ISO C++17 does not allow dynamic exception specifications
>   201 |   throw( FieldConvertError )
>       |   ^~~~~
> ```
> 
> Note that if I substitute `-std=c++11` or `-std=c++14` into the command above then it compiles without error.

This issue appears to be solved by this commit: a46708090444826c5f46a5dbf2ba4b069b413c58
https://github.com/quickfix/quickfix/tree/a46708090444826c5f46a5dbf2ba4b069b413c58

**Comment by sweemer** [comment]
Yes, now it just has to be released. That's why I asked @orenmnero to make a new release from master in my previous comment.

I would use master branch but since there are so many unreleased changes on it I can't be sure it's in a stable state. Creating a release version would help alleviate some of that concern for me.

**Comment by daniel-und-pav-at-cargill-dot-com** [comment]
this is going nowhere...

**Comment by McLeodD** [comment]
@daniel-und-pav-at-cargill-dot-com if you are using conan you can use quickfix from it. The 1.15.1 version actually applies the patches to support C++17. See: https://github.com/conan-io/conan-center-index/blob/master/recipes/quickfix/all/patches/0001-Fix-build-for-C-17-replace-throw-.-with-EXCEPT.patch

You could also apply this patch yourself.

@sweemer, @orenmnero: I agree though. I think a new release would be a good idea :crossed_fingers:. The last one was almost 5 years ago.

**Comment by daniel-und-pav-at-cargill-dot-com** [comment]
Now that these changes have been pushed by @orenmnero -- can we get a new tagged version?

**Comment by quickfix** [comment]
Yes, that’s why I’m reviewing and merging these PRs
