### ISSUE TITLE
MySQL8+ builds

### ISSUE THREAD

**Issue by lissom** [quickfix/quickfix#420]
For mysql 8+ my_bool has been removed and they recommend replacing with an int: https://bugs.mysql.com/bug.php?id=85131

Two approaches work (i.e. make check passes with both)
I don't have mysql 5 to test with, but 8 builds with both, and I'm not sure what you prefer (though 1 seems simpler):
1)
@@ -174,7 +174,7 @@ class MySQLConnection                                                                                               
           throw ConfigError( std::string("Unable to connect to database [") + mysql_error(m_pConnection) + "]" );                      
     }                                                                                                                                  
     #if( MYSQL_VERSION_ID > 50000 )                                                                                                    
-    my_bool reconnect = 1;                                                                                                             
+    char reconnect = 1;                                                                                                                
     mysql_options( m_pConnection, MYSQL_OPT_RECONNECT, static_cast<char*>(&reconnect) );                                               
     #endif                                                                                                                             
   }                           

2)
@@ -173,8 +173,11 @@ class MySQLConnection                                                                                              
         if( !connected() )
           throw ConfigError( std::string("Unable to connect to database [") + mysql_error(m_pConnection) + "]" );
     }                                                                                                                                  
-    #if( MYSQL_VERSION_ID > 50000 )                                                                                                    
-    my_bool reconnect = 1;                                                                                                                
+    #if( MYSQL_VERSION_ID > 80000 )                                                                                                    
+    int reconnect = 1;                                                                                                                 
+    mysql_options( m_pConnection, MYSQL_OPT_RECONNECT, static_cast<int*>(&reconnect) );                                                
+    #elif( MYSQL_VERSION_ID > 50000 )                                                                                                  
+    my_bool reconnect = 1;                                                                                                             
     mysql_options( m_pConnection, MYSQL_OPT_RECONNECT, static_cast<char*>(&reconnect) );
     #endif
   }

**Comment by orenmnero** [comment]
#448
