### ISSUE TITLE
 void operator+=( int seconds ) bug  in FieldTypes.h

### ISSUE THREAD

**Issue by Liu2Mao** [quickfix/quickfix#423]
`  void operator+=( int seconds )
  {
    int d = seconds / SECONDS_PER_DAY;
    int s = seconds % SECONDS_PER_DAY;

    m_date += d;
    m_time += s * NANOS_PER_SEC;

    if( m_time > NANOS_PER_DAY )
    {
      m_date++;
      m_time %= NANOS_PER_DAY;
    }
    else if( m_time < 0 )
    {
      m_date--;
      m_time += NANOS_PER_DAY;
    }
  }`

  if( m_time > NANOS_PER_DAY ) should be   if( m_time **>=** NANOS_PER_DAY )

**Comment by orenmnero** [comment]
#441
