### ISSUE TITLE
Is there any plan to release a new tag?

### ISSUE THREAD

**Issue by Cheney-W** [quickfix/quickfix#424]
The latest tag was released in 2018, so could you consider releasing a new tag that includes the latest commit?

**Comment by McLeodD** [comment]
I'm wondering the same thing. I have seen that @orenmnero merged a lot of PRs this week-end :partying_face:. Thank you a lot Oren for this, it reassures us that quickfix is still maintained! :slightly_smiling_face:
However, it would be great to have a new release. It seems kind of necessary now.

**Comment by orenmnero** [comment]
Yeah, I've merged all the PRs I want in this release. Now going through reported issues to see If there are any important ones to address.
