### ISSUE TITLE
Deprecate Python2?

### ISSUE THREAD

**Issue by McLeodD** [quickfix/quickfix#452]
Since Python2 is out of support since January 1, 2020. See [Sunsetting Python 2](https://www.python.org/doc/sunset-python-2/):
> We have decided that January 1, 2020, was the day that we sunset Python 2. That means that we will not improve it anymore after that day, even if someone finds a security problem in it. You should upgrade to Python 3 as soon as you can.

I think Quickfix could remove Python 2 support in its codebase (especially if keeping the support of it starts to be annoying).

**Comment by quickfix** [comment]
Not even security updates, that’s enough for me. If they aren’t supporting
it no need for us to.

**Comment by da4089** [comment]
Agree that Python2 support can be dropped: most users have moved to Python3 now, and almost all general-purpose packages no longer support Python2.

**Comment by orenmnero** [comment]
Yep, if someone wants to keep using python2, staying on QuickFIX 1.15.1 is perfectly reasonable as well.

Dropped: #455
