### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by leonbaum** [quickfix/quickfix#47]
Trying to build HEAD on 64bit Gentoo Linux, but running into a linking error:

```
Creating libUnitTest++.a library...
Linking TestUnitTest++...
Running unit tests...
terminate called after throwing an instance of 'char const*'
Makefile:79: recipe for target 'TestUnitTest++' failed
make[2]: *** [TestUnitTest++] Aborted
make[2]: *** Deleting file 'TestUnitTest++'
make[2]: Leaving directory '/var/tmp/portage/dev-libs/quickfix-9999/work/quickfix/UnitTest++'
Makefile:484: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/quickfix-9999/work/quickfix'
Makefile:392: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JohnRobson** [comment]
I have the same problem in Arch 64 bits

src/tests/TestCurrentTest.cpp
Linking TestUnitTest++...
Running unit tests...
terminate called after throwing an instance of 'char const*'
Makefile:79: recipe for target 'TestUnitTest++' failed
make[2]: *** [TestUnitTest++] Aborted (core dumped)
make[2]: *** Deleting file 'TestUnitTest++'
make[2]: Leaving directory '/tmp/tmp/qf/extract/quickfix/UnitTest++'
Makefile:495: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/tmp/qf/extract/quickfix'
Makefile:404: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ppanhoto78** [comment]
workaround: 
after running configure, change the file UnitTest++/Makefile:

$(test): $(lib) $(test_objects)
	@echo Linking $(test)...
	@$(CXX) $(LDFLAGS) -o $(test) $(test_objects) $(lib)
	@echo Running unit tests...
	@./$(test)

change the last line to #@./$(test) so it gets commented.
