### ISSUE TITLE
Including MySQLStore and MySQLLog with the Python Library

### ISSUE THREAD

**Issue by robertbetts** [quickfix/quickfix#51]
I have added MySQLStore, MySQLLog to the swig interface file on my local copy of quickfix 1.14.3.

I have not completed my testing of MySQLLog, however MySQLStore works great.

My question is why are these modules no included by default? If there is a reason,  it would be useful to know.

**Comment by charliegenge** [comment]
Hi robertbetts, would you mind giving some more details on what you changed exactly in the swig interface file?

**Comment by sbhujabal** [comment]
Hello @robertbetts

Is quickfix.i the swig interface file? or is there any other file where I am supposed to add my user defined Ecxeption handling code. 

waiting for your prompt response..###  thanks in advance :+1:

**Comment by robertbetts** [comment]
Hi @charliegenge @sbhujabal , I only just came across your questions. I can't remember where and how I made the changes. I can say that I ditched the idea. Logging messages and maintaining session/sequence information in the database was not as performant and robust as what we required.

**Comment by robertbetts** [comment]
@charliegenge @sbhujabal, I found the changes I made in a fork we did a few years back:

https://github.com/GenoaIO/quickfix/commit/e0c524732cb43698ec21fe0a88be8763bc57d754

**Comment by orenmnero** [comment]
#503
