### ISSUE TITLE
Fix Logon message not working

### ISSUE THREAD

**Issue by ninjadev0831** [quickfix/quickfix#526]
[DEFAULT]
ConnectionType=initiator
LogonTimeout=30
ReconnectInterval=30
FileLogPath=./connectors/lmax/Logs/
UseLocalTime=N

StartTime=00:00:00
EndTime=23:59:59

UseDataDictionary=Y
DataDictionary=FIX44.xml
FileStorePath=./connectors/lmax/Sessions/

[SESSION]
BeginString=FIX.4.4
SenderCompID=*********
Username=*********
Password=*********
TargetCompID=LMXBDM
StartTime=00:00:00
EndTime=23:59:59
HeartBtInt=30
CheckLatency=N
MaxLatency=240
SocketConnectPort=443
SocketConnectHost=fix-marketdata.london-demo.lmax.com

This is my config file, but when using it to login. I got this log.

(8=FIX.4.4 | 9=72 | 35=A | 34=45 | 49=******** | 52=20230921-05:33:29.000 | 56=LMXBDM | 98=0 | 108=30 | 10=132|)

As you can see the Tag 553, 554 was missing.

I am using quickfix python package.

This issues is because of the python package?

Please help me

**Comment by pdm-steve** [comment]
You need to implement that in your toAdmin function:

```
    def toAdmin(self, message, sessionID):
     msgType = fix.MsgType ()
     message.getHeader ().getField (msgType)
     if (msgType.getValue () == fix.MsgType_Logon):
        message.setField(fix.Username('***'))
        message.setField(fix.Password('***'))
        return
```
Copied from [here](https://ctrader.com/forum/fix-api/11072)
