### ISSUE TITLE
log output "NextExpectedMsgSeqNum too low" is wrong

### ISSUE THREAD

**Issue by pdm-steve** [quickfix/quickfix#564]
The log message in Session::nextLogon due to an invalid incoming NextExpectedMsgSeqNum is wrong. "NextExpectedMsgSeqNum too low" needs to be replaced with "NextExpectedMsgSeqNum too **high**"

See my comment:
https://github.com/quickfix/quickfix/commit/ba2b3273f8d7e457589861f9792885bf4c7209e2#comments

**Comment by orenmnero** [comment]
https://github.com/quickfix/quickfix/pull/584
