### ISSUE TITLE
Compilation Issues with OpenSSL Due to Source Code Errors in UtilitySSL Files

### ISSUE THREAD

**Issue by MukulZ18** [quickfix/quickfix#576]
## Description
When attempting to compile the QuickFIX library with OpenSSL support using the `--with-openssl` flag, I encountered compilation errors that prevented successful building and installation. Upon investigation, I identified two specific issues in the source code related to the handling of OpenSSL configurations. Resolving these issues allowed the library to compile successfully with OpenSSL support.

## Environment
- **Operating System:** Ubuntu 20.04 LTS
- **Compiler:** GCC 9.3.0
- **QuickFIX Commit Hash:** 9c37bd7bfff6da30b556fa0aad2bbb599ba50aec
- **OpenSSL Version:** 1.1.1f

## Steps to Reproduce
1. Configure the QuickFIX build with OpenSSL support using `./configure --with-openssl`.
2. Run `make` to compile the library.

## Expected Behavior
The library should compile without errors and link against the OpenSSL libraries.

## Actual Behavior
Compilation fails with errors in `UtilitySSL.h` and `UtilitySSL.cpp`, specifically:

1. A missing `#endif` directive in `UtilitySSL.h`.
2. Incorrect references to `TLSCipherSuites` in `UtilitySSL.cpp`, which should be `TLS_CIPHER_SUITES`.

### Error Output

The following errors were encountered during the compilation:

```plaintext
UtilitySSL.h:112: error: unterminated #ifndef
UtilitySSL.cpp:1162: error: ‘TLSCipherSuites’ was not declared in this scope
UtilitySSL.cpp:1164: error: ‘TLSCipherSuites’ was not declared in this scope
```

## Proposed Solution
1. **For the missing `#endif`:**
   - Add an `#endif` at line 237 of `UtilitySSL.h` to resolve the error.

2. **For the incorrect references in `UtilitySSL.cpp`:**
   - Replace all instances of `TLSCipherSuites` with `TLS_CIPHER_SUITES` to match the correct variable name defined in `SessionSettings.h`

These modifications resolved the compilation errors and allowed the library to build successfully with OpenSSL support.

### Patch/Suggested Changes
```diff
--- a/src/C++/UtilitySSL.h
+++ b/src/C++/UtilitySSL.h
@@ -234,7 +234,7 @@ int setSocketNonBlocking(socket_handle pSocket);
 #   define SSL_PROTOCOL_ALL                                                        \
       (SSL_PROTOCOL_SSLV2 | SSL_PROTOCOL_SSLV3 | SSL_PROTOCOL_TLSV1 |              \
        SSL_PROTOCOL_TLSV1_1 | SSL_PROTOCOL_TLSV1_2)
-
+#endif
 typedef enum {
   SSL_CLIENT_VERIFY_NONE = 0,
   SSL_CLIENT_VERIFY_REQUIRE = 1,

--- a/src/C++/UtilitySSL.cpp
+++ b/src/C++/UtilitySSL.cpp
@@ -1159,9 +1159,9 @@ SSL_CTX *createSSLContext(bool server, const SessionSettings &settings,
     }
   }
 
-  if (settings.get().has(TLSCipherSuites))
+  if (settings.get().has(TLS_CIPHER_SUITES))
   {
-    std::string strCipherSuites = settings.get().getString(TLSCipherSuites);
+    std::string strCipherSuites = settings.get().getString(TLS_CIPHER_SUITES);
 
 #if (OPENSSL_VERSION_NUMBER >= 0x1010100FL)
     if (!strCipherSuites.empty() &&

**Comment by pps314159** [comment]
In fact, I am a bit concerned with the changes of the last year because I get an impression that the changes are not properly verified/tested. Broken compilation sounds like a thing that should not happen in committed code. I have few cases of some broken scenarios related to migration to poll (from select) on UNIXes and introduction of OS-separated socket monitoring (done in a way leading to significant code duplication, BTW).

**Comment by orenmnero** [comment]
https://github.com/quickfix/quickfix/pull/570
