### ISSUE TITLE
quickfix unable to connect with CQG FIX API because of missing variables

### ISSUE THREAD

**Issue by williamwood00** [quickfix/quickfix#617]
I am trying to connect to the CQG FIX API. My python code works fine with StoneX. However, the login for CQG requires some additional parameters: 

SenderSubID = (value) 
RawData = (value)

Although the FIX number code for these is included within the SWIG-generated quickfix.py, the actual variables are not:

SENDERCOMPID = cvar.SENDERCOMPID (This variable is used) 
SENDERSUBID = cvar.SENDERSUBID (This line is MISSING)

This is also missing in the sessionsettings.h file. When I add the appropriate lines to sessionsettings.h, the swig script "swig.sh" generates a new quickfix.py with the appropriate lines: 

SENDERSUBID = cvar.SENDERSUBID

HOWEVER, when I try to include this new quickfix in the python program, I get the following error: 

delete_SwigPyIterator module not in _quickfix

I downgraded to Swig 3.0.10, which is the version that generated the original quickfix that works, and I get the same error message. Any help with this problem would be much appreciated...

**Comment by mgatny** [comment]
SenderSubID and RawData are not SessionSsettings.  That is, you do not (and cannot) set them via the cfg file.  You set them yourself, like any other field on the message(s) your are sending.

If you want SenderSubID on every message you send, you can set it in toApp() and toAdmin().

If you want RawData on e.g. the Logon you send, check if the MsgType is a Logon in toAdmin(), and then set the RawData field if it is.

Remember that SenderSubID and MsgType are in the header of the message and RawData is in the body.

**Comment by williamwood00** [comment]
Mike -
I appreciate the reply.  The problem I am having is that I am constrained to use python, and the only FIX engine I have found is the quickfix package which is written in C++, and wrapped with SWIG.  Within this framework, the only access to a session is through the initial logon stream.  Because CQG requires the SenderSubID in the initial logon, if it is not present, the user is not logged on, and the engine traps the user in an endless loop waiting to log on.  The only solution that I can see here is to rewrite that part of the C++ code, and wrap it with SWIG.  The scripts for wrapping with SWIG I have not been able to make work for the unchanged distribution programs, so it is not clear that proceeding along this line is possible for me.
  Your suggestion of using toAdmin() is subject to the same constraint.  The only access to this message stream requires a sessionID input, but the quickfix engine does not accept user supplied input for this, only internally generated values.  I am able to get the sessionID variable out from the program, but I am unable to create a toAdmin() stream with the user ID because of this input issue.  I am not sure how to proceed at this point...

**Comment by mgatny** [comment]
If you want SenderSubID (or any other Field) to be present on the Logon your app sends, do this:

```python
class Application(fix.Application):
	def toAdmin(self, sessionID, message):
		msgType = fix.MsgType()
		message.getField(msgType)
		if msgType.getValue() == fix.MsgType_LOGON:
			message.getHeader().setField(fix.SenderSubID("YourSenderSubID"))
```

The `toAdmin` callback is called by quickfix right before it sends any Admin-level message.  This is your opportunity to add/remove Fields before the message is sent.  You do not need to modify the C++ code or SWIG to do this.
