### ISSUE TITLE
XMLNonFIX message not parsed correctly

### ISSUE THREAD

**Issue by udpip7** [quickfix/quickfix#62]
I received an XMLNonFIX message that contains a FIX message wrapped in an XML element as the XMLData and that it not parsed correctly.  The XMLData field in the header stops at the first embedded SOH and then the remained of the embedded FIX gets parsed in to the body of the enclosing message.

replace pipes with SOH in the example message below:

<pre>
8=FIX.4.2|9=514|35=n|34=158|369=130|52=20150220-14:40:24.991|49=CME|50=G|56=QQQQQQN|57=QQQ|212=426|213=&lt;RTRF&gt;8=FIX.4.2|9=390|35=8|34=136|369=131|52=20150220-14:40:24.991|49=CME|50=G|56=GGGGGGN|57=GGG|143=IL|1=TEST|6=0|11=00000000000000000003|14=1|17=64485:M:412850TN0031303|20=0|31=208700|32=1|37=64227619161|38=1|39=2|40=2|41=0|44=208700|48=147403|54=1|55=ES|59=0|60=20150220-14:40:24.970|75=20150220|107=ESH5|150=2|151=0|167=FUT|337=TRADE|375=CME000A|432=20150220|442=1|527=642276191612015022031303|1028=N|1057=N|10=000|&lt;/RTRF&gt;|10=111|
</pre>

**Comment by udpip7** [comment]
I believe this is because that the XMLData field is not being parsed as a data field.  In Message.cpp, in extractField when the length field is looked up it doesn't look in the header of the message so it can't find tag 212 and so it just parses it as a normal tag value.

**Comment by Ambal** [comment]
Hi, udpip7.

I'm working on generic code which should parse all data-type fields correctly disregarding its location (body, header, trailer).

I'm looking at your message above and it seems to have invalid XmlDataLength field value of 426 while message contained in XmlData field has total length of only 413 symbols. 

Please, provide correct XmlNonFix message for investigation

**Comment by udpip7** [comment]
github's formatting swallowed part of the message because it was an XML tag.  I've replaced the symbols with entities so you can see the full message; that restores the missing 13 characters.

**Comment by Ambal** [comment]
hi, udpip7. Now I get error that checksum is invalid ( actual is 111 but quickfix calculates it as 40 ). Are you sure the checksum in the message above is correct?

**Comment by udpip7** [comment]
The checksum above is not correct.  The message isn't an exact copy of what was in my test environment; I changed the identity of the session before posting.  You're saying that with your fixes it parses correctly, right?

**Comment by Ambal** [comment]
Hi, udpip7. Yes, mine code parse the above message just fine, the only issue is invalid checksum (should be 40 instead of 111). Cheers.
