### ISSUE TITLE
Visual Studio 2015 Support

### ISSUE THREAD

**Issue by mahl** [quickfix/quickfix#77]
Is there a plan to support Visual Studio 2015?

**Comment by msnelling** [comment]
+1 for VS2015 support

**Comment by wxianxin** [comment]
+1 for VS 2015 support.
Anyone knows a way around this except installing older VS version?

**Comment by Ambal** [comment]
VS2015 can easily convert any existing solution files with corresponding VC projects e.g. "quickfix_vs12.sln". No code changes are required.

**Comment by orenmnero** [comment]
We have supported this for a while now, closing.
