### ISSUE TITLE
make check failed

### ISSUE THREAD

**Issue by andyyuan78** [quickfix/quickfix#78]
make[6]: Nothing to be done for `all-am'.
make[6]: Leaving directory`/home/ubgpu/github/quickfix/test'
make[5]: Leaving directory `/home/ubgpu/github/quickfix/test'
ERROR: unknown command line flag 'l'
ERROR: unknown command line flag 'l'
ERROR: unknown command line flag 'l'
ERROR: unknown command line flag 'l'
ERROR: unknown command line flag 'l'
ERROR: unknown command line flag 'l'
ERROR: unknown command line flag 'l'
# /bin/bash: line 11: test: +: integer expression expected
# Testsuite summary for QuickFIX 1.14.3

/bin/bash: line 28: test: : integer expression expected
# TOTAL:

/bin/bash: line 28: test: : integer expression expected
# PASS:

/bin/bash: line 28: test: : integer expression expected
# SKIP:

/bin/bash: line 28: test: : integer expression expected
# XFAIL:

/bin/bash: line 28: test: : integer expression expected
# FAIL:

/bin/bash: line 28: test: : integer expression expected
# XPASS:

/bin/bash: line 28: test: : integer expression expected
# ERROR:
# 

See test/test-suite.log
# Please report to ask@quickfixengine.org

make[4]: **\* [test-suite.log] Error 1
make[4]: Leaving directory `/home/ubgpu/github/quickfix/test'
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory`/home/ubgpu/github/quickfix/test'
make[2]: **\* [check-am] Error 2
make[2]: Leaving directory `/home/ubgpu/github/quickfix/test'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory`/home/ubgpu/github/quickfix/test'
make: **\* [check-recursive] Error 1
ubgpu@ubgpu:~/github/quickfix$

**Comment by smitvora1904** [comment]
I am also facing same issue
