### ISSUE TITLE
build failed & run crash in vs2015

### ISSUE THREAD

**Issue by dododunk** [quickfix/quickfix#81]
maybe vs2015 changed its __beginthreadex   function signature, which causes compile error.
so in my emergent suit case, just  change source code into 
bool thread_spawn(_beginthreadex_proc_type func, void\* var, thread_id& thread )
{
# ifdef _MSC_VER

  thread_id result = 0;
  unsigned int id = 0;
  result = _beginthreadex( NULL, 0, func, var, 0, &id );
  if ( result == 0 ) return false;
in file  Utility.cpp .

**Comment by markdays** [comment]
result = _beginthreadex( NULL, 0, (_beginthreadex_proc_type)func, var, 0, &id );
