### ISSUE TITLE
Does anyone have sample code for ICE order routing by using Quickfix engine?

### ISSUE THREAD

**Issue by dxwu88** [quickfix/quickfix#86]

**Comment by tanbench** [comment]
do you find the way to solve this question？
I also want to use quickfix to connect CME order routing.

**Comment by dxwu88** [comment]
No. I didn't. If I find anything, i'll let you know.

Sent from my iPhone

On Mar 16, 2016, at 12:48 AM, tanbench <notifications@github.com<mailto:notifications@github.com>> wrote:


do you find the way to solve this question?
I also want to use quickfix to connect CME order routing.

-
