### ISSUE TITLE
Building with CMake

### ISSUE THREAD

**Issue by rockdreamer** [quickfix/quickfix#88]
Hi,
I'd like to make a CMake build script.

Rationale:
- quickfix runs on multiple unix-like platforms, plus windows and mac os
- microsoft has released VS2015 and there is still no official support for it (or at least, it's not clear that the existing solutions are operational). CMake abstracts all this.

I'll be working on this on a separate branch. This ticket is for discussion :)

**Comment by muratkarakus7** [comment]
While developing this feature, could you please employ **small atomic commits** approach so that upcoming contributors can understand the development process.

**Comment by kariya2** [comment]
any updates on cmake?
