### ISSUE TITLE
How to add custom FIX message field?

### ISSUE THREAD

**Issue by supermartzin** [quickfix/quickfix#96]
Hi!

I am using a QuickFIX in my application and I would like to add a new custom Field -> **AccountBalance** of type `AMT` to **RequestForPositionsAck** message.

Could you please give me an advice how can I do it? 
I cannot find any helpful material about this and also I cannot find the implementations of other existing fields that I could get inspired from.

Thanks in advance! :)

**Comment by SternAndrew** [comment]
Found this using google 'quickfix custom fields'.  I think this is what your looking for: http://www.quickfixengine.org/quickfix/doc/html/user_defined.html

**Comment by supermartzin** [comment]
Thanks! 
I have probably omitted that article when I have been searching for this information.
Looks like it's working fine so far.

+ thanks for the reminder of setting my field in XML DataDictionary
