### ISSUE TITLE
how to include ssl certificate to python quickfix

### ISSUE THREAD

**Issue by ukrit-himakoon** [quickfix/quickfix#98]
Is there any configuration parameter or userguide for this? 

Thanks.

**Comment by Ambal** [comment]
Hi. Unfortunately SSL is not supported by current quickfix source code. You need to use SSL proxy like 'stunnel' instead.

**Comment by smorrel1** [comment]
+1 on this. 

Since 2016 the SSL equivalents of (Threaded)SocketInitiator/Acceptor have been added for C++. Thanks @karopawil for a great contribution!! 

I'd add the SSL .h and .cpp files myself but not that familiar with 'make', swig, etc. Thanks.

**Comment by Pk13055** [comment]
Any updates on this? Has someone been able to get SSL working with `fix.SocketInitiator`?  If you've used SSL tunneling, please do share how you set it up to work. TIA!

**Comment by cebaa** [comment]
@Pk13055 Looks like the python build doesn't include `SSLSocketInitiator` / `SSLSocketAcceptor`. Not sure if that's a limitation of the way it's built or something else.
