### ISSUE TITLE
Problem with aclocal

### ISSUE THREAD

**Issue by dendisuhubdy** [quickfix/quickfix#99]
C02QH2D7G8WM:quickfix userone$ ./bootstrap
- case `uname` in
  ++ uname
- glibtoolize --copy
  glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
  glibtoolize: copying file 'config/ltmain.sh'
- autoreconf -i -Wall,no-obsolete
  Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
  autoreconf: failed to run aclocal: No such file or directory

**Comment by EmilyWebber** [comment]
I have the same problem. Any suggestions on what to do from this point? Running a mac

**Comment by orenmnero** [comment]
You must install auto tools if you want to run bootstrap.
